// ADO-72 P05 — Filtro Corredor
// Generated by playwright_test_generator.py v1.1.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/72/scenarios.json --ui-maps cache/ui_maps/ --out evidence/72/tests/
// Screen: FrmAgenda.aspx


import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

// ORACLE_PROBES — generated from scenario.oraculos × ui_map.
// Consumed by the test.afterEach hook to write
// evidence/<ticket>/<sid>/assertions_<sid>.json with the actual values
// captured from the live DOM, regardless of whether the test passed,
// failed, or threw. uat_assertion_evaluator.py reads this file as the
// primary source of truth for expected/actual reconciliation; without
// it every oracle would default to status=review.
type OracleProbe = {
  oracle_id: number;
  target: string;
  tipo: string;
  expected: string | number | null;
  selector: string | null;  // CSS-ish; null for whole-page oracles
};
const ORACLE_PROBES: OracleProbe[] = [

  {
    oracle_id: 0,
    target: "table_agenda_usu",
    tipo: "count_eq",
    expected: 0,
    selector: "#c_GridAgendaUsu"
  },

  {
    oracle_id: 1,
    target: "panel_gvc_agenda_usu",
    tipo: "visible",
    expected: null,
    selector: "#__gvc_GridAgendaUsu__div"
  },

];
const ASSERTIONS_OUT_PATH = 'evidence/72/P05/assertions_P05.json';

// STEP_BBOXES — accumulates bounding boxes of interacted elements per step.
// Written by test.afterEach to evidence/<ticket>/<sid>/step_bboxes.json and
// consumed by screenshot_annotator.py (Fase 2) to draw red boxes on screenshots.
type StepBboxEntry = {
  step_index: number;
  screenshot_path: string;
  target: string;
  bbox: { x: number; y: number; width: number; height: number } | null;
};
const STEP_BBOXES: StepBboxEntry[] = [];
const STEP_BBOXES_OUT_PATH = 'evidence/72/P05/step_bboxes.json';


test.describe('ADO-72 | P05 — Filtro Corredor', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p05 filtro_corredor', async ({ page }) => {
    // DATA: N/A

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    
    // - ConCorredor=0 en DEV
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/72/P05/step_00_setup.png' });

    // Expand "Búsqueda Avanzada" panel only when needed.
    // Some Agenda layouts don't expose data-toggle attrs, so use resilient fallback.
    const advancedPanel = page.locator('#c_pnlBusqueda');
    const firstFilter = page.locator('#c_ddlDebitoAuto, #c_abfCorredor, #c_abfNombreCliente, #c_abfRUC, #c_btnOk');
    let filtersReady = await firstFilter.first().isVisible().catch(() => false);
    if (!filtersReady) {
      const toggleByHeader = page.locator('.collapsible-header:has-text("Búsqueda Avanzada"), li:has-text("Búsqueda Avanzada") .collapsible-header').first();
      const toggleByData = page.locator('[data-toggle="collapse"][href="#c_pnlBusqueda"], [data-toggle="collapse"][data-target="#c_pnlBusqueda"]').first();
      const toggleByText = page.getByText('Búsqueda Avanzada', { exact: false }).first();

      if (await toggleByHeader.count()) {
        await toggleByHeader.scrollIntoViewIfNeeded();
        await toggleByHeader.click({ timeout: 5000, force: true });
      } else if (await toggleByData.count()) {
        await toggleByData.click({ timeout: 5000, force: true });
      } else if (await toggleByText.count()) {
        await toggleByText.click({ timeout: 5000, force: true });
      }

      if (await advancedPanel.count()) {
        await advancedPanel.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
      }
      filtersReady = await firstFilter.first().isVisible().catch(() => false);

      // Last-resort fallback for legacy WebForms layouts where the toggle
      // exists but does not update aria/visibility attributes consistently.
      if (!filtersReady && await advancedPanel.count()) {
        await page.evaluate(() => {
          const pnl = document.querySelector('#c_pnlBusqueda') as HTMLElement | null;
          if (pnl) {
            pnl.style.display = 'block';
            pnl.classList.add('active');
          }
        });
        filtersReady = await firstFilter.first().isVisible().catch(() => false);
      }
    }
    console.log('Advanced filters ready:', filtersReady);
    await page.screenshot({ path: 'screenshots/P05_panel_expanded.png' });

    // ACTION
    
    
    // [STEP 01] click link_c_btnok
    console.log('[STEP 01] click link_c_btnok');
    await page.locator("#c_btnOk").click({ force: true });
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/72/P05/step_01_after.png' });
    STEP_BBOXES.push({ step_index: 1, screenshot_path: 'evidence/72/P05/step_01_after.png', target: "link_c_btnok", bbox: await page.locator("#c_btnOk").boundingBox().catch(() => null) });
    
    
    

    // ASSERTIONS
    
    
    {
      const rowCount = await page.locator('#c_GridAgendaUsu tbody tr').count();
      await expect(rowCount, 'P05: table_agenda_usu rows debe ser == 0').toBe(0);
    }
    
    
    
    await expect(page.locator('#__gvc_GridAgendaUsu__div'), 'P05: panel_gvc_agenda_usu debe ser visible').toBeVisible();
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    // Capture final state screenshot first — fail-safe even if the page is
    // mid-PostBack.
    try {
      await page.screenshot({
        path: 'evidence/72/P05/step_final_state.png',
      });
    } catch (_e) {
      // ignore — page may be closed or navigating
    }

    // ASSERTIONS EVIDENCE — capture actual values for every oracle so
    // uat_assertion_evaluator.py can reconcile expected vs actual without
    // relying on Playwright's pass/fail (which conflates product defects
    // with pipeline defects).
    const captured: any[] = [];
    for (const probe of ORACLE_PROBES) {
      const entry: any = {
        oracle_id: probe.oracle_id,
        target: probe.target,
        tipo: probe.tipo,
        expected: probe.expected,
      };
      try {
        if (probe.selector === null) {
          // Whole-page oracle: capture the body text once (truncated).
          const bodyText = (await page.locator('body').innerText({ timeout: 2000 })) || '';
          entry.actual_text = bodyText.slice(0, 4000);
          entry.visible = true;
        } else {
          const loc = page.locator(probe.selector);
          // count
          const count = await loc.count();
          entry.count = count;
          if (count === 0) {
            entry.visible = false;
            entry.actual_text = null;
          } else {
            entry.visible = await loc.first().isVisible({ timeout: 2000 });
            // value (form controls)
            try {
              entry.value = await loc.first().inputValue({ timeout: 1000 });
            } catch (_e) { /* not a form control */ }
            // textContent
            try {
              const txt = (await loc.first().innerText({ timeout: 1500 })) || '';
              entry.actual_text = txt.slice(0, 1000);
            } catch (_e) {
              entry.actual_text = null;
            }
            // disabled / state
            try {
              entry.state = (await loc.first().isDisabled({ timeout: 500 })) ? 'disabled' : 'enabled';
            } catch (_e) { /* ignore */ }
          }
        }
      } catch (e: any) {
        entry.capture_error = String(e && e.message ? e.message : e).slice(0, 300);
      }
      captured.push(entry);
    }

    // Persist assertions_<sid>.json. mkdir is safe-recursive; failures here
    // must not break the test runner.
    try {
      const outPath = path.resolve(process.cwd(), ASSERTIONS_OUT_PATH);
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(
        outPath,
        JSON.stringify(
          { scenario_id: 'P05', assertions: captured },
          null, 2,
        ),
        'utf-8',
      );
    } catch (e) {
      console.error('[afterEach] could not persist assertions json:', e);
    }

    // Persist step_bboxes.json for screenshot_annotator.py (Fase 2).
    // Non-fatal: if this fails the pipeline continues without annotations.
    if (STEP_BBOXES.length > 0) {
      try {
        const bboxOutPath = path.resolve(process.cwd(), STEP_BBOXES_OUT_PATH);
        fs.mkdirSync(path.dirname(bboxOutPath), { recursive: true });
        fs.writeFileSync(bboxOutPath, JSON.stringify(STEP_BBOXES, null, 2), 'utf-8');
      } catch (e) {
        console.error('[afterEach] could not persist step_bboxes json:', e);
      }
    }


    await page.context().clearCookies();
  });
});