// ADO-70 P01 — Abrir FrmAgenda.aspx sin click - grillas pueden estar vacias pero NO aparece mensaje de lista vacia.
// Generated by playwright_test_generator.py v1.0.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/70/scenarios.json --ui-maps cache/ui_maps/ --out evidence/70/tests/
// Screen: FrmAgenda.aspx

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

test.describe('ADO-70 | P01 — Abrir FrmAgenda.aspx sin click - grillas pueden estar vacias pero NO aparece mensaje de lista vacia.', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p01 abrir_frmagenda.aspx_sin_click_-_grillas_pueden_estar_vacias', async ({ page }) => {
    // DATA: N/A

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/70/P01/step_00_setup.png' });

    // ACTION
    
    
    // [STEP 01] wait visible panel_c_lblagendaaut
    await expect(page.locator('#c_lblAgendaAut')).toBeVisible({ timeout: 10000 });
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('#c_lblAgendaUsu'), 'P01: panel_c_lblagendausu no debe ser visible').toBeHidden();
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    await page.screenshot({ path: 'evidence/70/P01/step_final_state.png' });
    await page.context().clearCookies();
  });
});