// ADO-70 P04 — FechaDesde=19000101, FechaHasta=19000101, click Buscar - debe aparecer mensaje &quot;No hay lotes agendados que cumplan los criterios seleccionados&quot; como Aviso.
// Generated by playwright_test_generator.py v1.0.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/70/scenarios.json --ui-maps cache/ui_maps/ --out evidence/70/tests/
// Screen: FrmAgenda.aspx

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

test.describe('ADO-70 | P04 — FechaDesde=19000101, FechaHasta=19000101, click Buscar - debe aparecer mensaje &quot;No hay lotes agendados que cumplan los criterios seleccionados&quot; como Aviso.', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p04 fechadesde=19000101,_fechahasta=19000101,_click_buscar_-_deb', async ({ page }) => {
    // DATA: N/A

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/70/P04/step_00_setup.png' });

    // ACTION
    
    
    // [STEP 01] fill input_desde with "19000101"
    console.log('[STEP 01] fill input_desde');
    await page.locator("#c_abfDesde").fill('19000101');;
    await page.screenshot({ path: 'evidence/70/P04/step_01_after.png' });
    
    
    
    // [STEP 02] fill input_hasta with "19000101"
    console.log('[STEP 02] fill input_hasta');
    await page.locator("#c_abfHasta").fill('19000101');;
    await page.screenshot({ path: 'evidence/70/P04/step_02_after.png' });
    
    
    
    // [STEP 03] click link_c_btnok
    console.log('[STEP 03] click link_c_btnok');
    await page.locator("#c_btnOk").click();
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/70/P04/step_03_after.png' });
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('#dialogFinSesion'), 'P04: panel_dialogfinsesion debe ser visible').toBeVisible();
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    await page.screenshot({ path: 'evidence/70/P04/step_final_state.png' });
    await page.context().clearCookies();
  });
});