// ADO-70 P05 — Aplicar filtros, navegar fuera, volver - todos los DDL muestran Todos/Todas.
// Generated by playwright_test_generator.py v1.0.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/70/scenarios.json --ui-maps cache/ui_maps/ --out evidence/70/tests/
// Screen: FrmAgenda.aspx

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

test.describe('ADO-70 | P05 — Aplicar filtros, navegar fuera, volver - todos los DDL muestran Todos/Todas.', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p05 aplicar_filtros,_navegar_fuera,_volver_-_todos_los_ddl_muest', async ({ page }) => {
    // DATA: N/A

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/70/P05/step_00_setup.png' });

    // ACTION
    
    
    // [STEP 01] click link_ddlacciones
    console.log('[STEP 01] click link_ddlacciones');
    await page.locator("#ddlAcciones").click();
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/70/P05/step_01_after.png' });
    
    
    
    // [STEP 02] wait load
    await page.waitForLoadState('load');
    
    
    
    // [STEP 03] click link_btnnext
    console.log('[STEP 03] click link_btnnext');
    await page.locator("#btnNext").click();
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/70/P05/step_03_after.png' });
    
    
    
    // [STEP 04] wait load
    await page.waitForLoadState('load');
    
    
    
    // [STEP 05] click link_btnnext
    console.log('[STEP 05] click link_btnnext');
    await page.locator("#btnNext").click();
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/70/P05/step_05_after.png' });
    
    
    
    // [STEP 06] wait load
    await page.waitForLoadState('load');
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('#c_ddlEmpresa'), 'P05: select_empresa debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_ddlNivelMora'), 'P05: select_nivel_de_mora debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_ddlPerfil'), 'P05: select_perfil debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_ddlRecomendacion'), 'P05: select_recomendaci_n debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_ddlRegion'), 'P05: select_regi_n debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_ddlTipoCliente'), 'P05: select_tipo_de_cliente debe ser visible').toBeVisible();
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    await page.screenshot({ path: 'evidence/70/P05/step_final_state.png' });
    await page.context().clearCookies();
  });
});