// ADO-120 P10 — Actualizacion de datos tras batch nocturno
// Generated by playwright_test_generator.py v1.1.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/120/scenarios.json --ui-maps cache/ui_maps/ --out evidence/120/tests/
// Screen: FrmDetalleClie.aspx


import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';


const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');



// NOTE: AGENDA_WEB_USER / AGENDA_WEB_PASS are used only by playwright/global.setup.ts
// for the one-time login.  Specs restore auth from storageState — no login here.

/**
 * waitForAgendaStable — Wait for AgendaWeb / ASP.NET WebForms to settle.
 *
 * Replaces raw waitForLoadState('load') which misses UpdatePanel async PostBacks.
 * Strategy:
 *   1. Wait for DOM content parsed (domcontentloaded — fast, reliable).
 *   2. Wait for ASP.NET PageRequestManager async PostBack to finish (UpdatePanel).
 *   3. Fail-safe: if Sys is not available, resolve immediately (static pages).
 */
async function waitForAgendaStable(page: any, timeout = 10_000): Promise<void> {
  await page.waitForLoadState('domcontentloaded').catch(() => null);
  await page.waitForFunction(
    () => {
      try {
        const prm = (window as any).Sys?.WebForms?.PageRequestManager?.getInstance?.();
        return !prm || !prm.get_isInAsyncPostBack();
      } catch (_) {
        return true;  // Sys not available — page is stable
      }
    },
    null,
    { timeout },
  ).catch(() => null);  // Never fail the test on this wait — it's best-effort
}

// ORACLE_PROBES — generated from scenario.oraculos × ui_map.
// Consumed by the test.afterEach hook to write
// evidence/<ticket>/<sid>/assertions_<sid>.json with the actual values
// captured from the live DOM, regardless of whether the test passed,
// failed, or threw. uat_assertion_evaluator.py reads this file as the
// primary source of truth for expected/actual reconciliation; without
// it every oracle would default to status=review.
type OracleProbe = {
  oracle_id: number;
  target: string;
  tipo: string;
  expected: string | number | null;
  selector: string | null;  // CSS-ish; null for whole-page oracles
};
const ORACLE_PROBES: OracleProbe[] = [

  {
    oracle_id: 0,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGCANAL",
    selector: null
  },

  {
    oracle_id: 1,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGMEDIOPAGO",
    selector: null
  },

  {
    oracle_id: 2,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGDEBAUT_DESC",
    selector: null
  },

  {
    oracle_id: 3,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de DESALDOFAVOR",
    selector: null
  },

  {
    oracle_id: 4,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGCUOTA",
    selector: null
  },

  {
    oracle_id: 5,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGMONTOCUOTA",
    selector: null
  },

  {
    oracle_id: 6,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGCORREDOR",
    selector: null
  },

  {
    oracle_id: 7,
    target: "input_nombre",
    tipo: "page_contains_text",
    expected: "nuevo valor de OGNROCUOTAS",
    selector: null
  },

];
const ASSERTIONS_OUT_PATH = 'evidence/120/P10/assertions_P10.json';

// STEP_BBOXES — accumulates bounding boxes of interacted elements per step.
// Written by test.afterEach to evidence/<ticket>/<sid>/step_bboxes.json and
// consumed by screenshot_annotator.py (Fase 2) to draw red boxes on screenshots.
type StepBboxEntry = {
  step_index: number;
  screenshot_path: string;
  target: string;
  bbox: { x: number; y: number; width: number; height: number } | null;
};
const STEP_BBOXES: StepBboxEntry[] = [];
const STEP_BBOXES_OUT_PATH = 'evidence/120/P10/step_bboxes.json';


// TARGET_SCREEN for this spec (declared by scenario — not inferred at runtime).
// The runner validates that the playbook/navigation arrives at this exact screen.
const TARGET_SCREEN = 'FrmDetalleClie.aspx';

test.describe('ADO-120 | P10 — Actualizacion de datos tras batch nocturno', () => {

  test.beforeEach(async ({ page }) => {
    // Auth is restored from storageState (written by playwright/global.setup.ts).
    // NO login here — the session is already established.
    // beforeEach navigates to the DECLARED target screen (not a hardcoded fallback).
    // If we are redirected to login, the session expired — fail immediately.
    await page.goto(`${BASE_URL}${TARGET_SCREEN}`, { waitUntil: 'domcontentloaded', timeout: 20_000 });
    await waitForAgendaStable(page);
    const beforeEachUrl = page.url().toLowerCase();
    if (beforeEachUrl.includes('frmlogin')) {
      throw new Error(
        `[${TARGET_SCREEN}] Session expired before test start. ` +
        'Re-run the pipeline to refresh auth (global.setup.ts). ' +
        'DO NOT re-run login in specs.',
      );
    }
    // Verify we actually reached the target screen (not a redirect to another page).
    if (!beforeEachUrl.includes(TARGET_SCREEN.toLowerCase().replace('.aspx', ''))) {
      throw new Error(
        `[WRONG_SCREEN] Expected to reach ${TARGET_SCREEN} but landed on: ${page.url()}. ` +
        'Verify the playbook navigation steps and the declared target_screen.',
      );
    }
  });

  test('p10 actualizacion_de_datos_tras_batch_nocturno', async ({ page }) => {
    // DATA: lote = 'V000000201605P'

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    
    // - El usuario ha visualizado la Vista Obligaciones de un lote determinado antes de la ejecución del batch nocturno.
    

    // ── Exception & network listener setup ──────────────────────────────────
    // stepRef permite a los listeners pasivos (response / pageerror / console)
    // registrar en qué step de acción ocurrió el evento, sin pasar `page` al
    // cierre del listener.


    // SETUP
    await page.goto(`${BASE_URL}FrmDetalleClie.aspx`, { waitUntil: 'domcontentloaded' });
    await waitForAgendaStable(page);

    await page.screenshot({ path: 'evidence/120/P10/step_00_setup.png' });

    // TARGET SCREEN VALIDATION — fail fast if wrong screen reached after navigation.
    {
      const setupUrl = page.url().toLowerCase();
      if (setupUrl.includes('frmlogin')) {
        throw new Error(
          `[BLOCKED_LOGIN_FAILED] Navigation to ${TARGET_SCREEN} redirected to login page. ` +
          'Session is invalid. Re-run the pipeline (do NOT add login logic to specs).',
        );
      }
      if (!setupUrl.includes(TARGET_SCREEN.toLowerCase().replace('.aspx', ''))) {
        throw new Error(
          `[BLOCKED_WRONG_SCREEN] Expected: ${TARGET_SCREEN} — Got: ${page.url()}. ` +
          'Check the playbook navigation steps or the declared target_screen.',
        );
      }
    }

    // Expand "Búsqueda Avanzada" panel only when needed.
    // Some Agenda layouts don't expose data-toggle attrs, so use resilient fallback.
    const advancedPanel = page.locator('#c_pnlBusqueda');
    const firstFilter = page.locator('#c_ddlDebitoAuto, #c_abfCorredor, #c_abfNombreCliente, #c_abfRUC, #c_btnOk');
    let filtersReady = await firstFilter.first().isVisible().catch(() => false);
    if (!filtersReady) {
      const toggleByHeader = page.locator('.collapsible-header:has-text("Búsqueda Avanzada"), li:has-text("Búsqueda Avanzada") .collapsible-header').first();
      const toggleByData = page.locator('[data-toggle="collapse"][href="#c_pnlBusqueda"], [data-toggle="collapse"][data-target="#c_pnlBusqueda"]').first();
      const toggleByText = page.getByText('Búsqueda Avanzada', { exact: false }).first();

      if (await toggleByHeader.count()) {
        await toggleByHeader.scrollIntoViewIfNeeded();
        await toggleByHeader.click({ timeout: 5000 });
      } else if (await toggleByData.count()) {
        await toggleByData.scrollIntoViewIfNeeded();
        await toggleByData.click({ timeout: 5000 });
      } else if (await toggleByText.count()) {
        await toggleByText.click({ timeout: 5000 });
      }

      if (await advancedPanel.count()) {
        await advancedPanel.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
      }
      filtersReady = await firstFilter.first().isVisible().catch(() => false);

      // Last-resort fallback for legacy WebForms layouts where the toggle
      // exists but does not update aria/visibility attributes consistently.
      if (!filtersReady && await advancedPanel.count()) {
        await page.evaluate(() => {
          const pnl = document.querySelector('#c_pnlBusqueda') as HTMLElement | null;
          if (pnl) {
            pnl.style.display = 'block';
            pnl.classList.add('active');
          }
        });
        filtersReady = await firstFilter.first().isVisible().catch(() => false);
      }
    }
    console.log('Advanced filters ready:', filtersReady);
    await page.screenshot({ path: 'screenshots/P10_panel_expanded.png' });

    // ACTION
    
    
    // [STEP 01] navigate to FrmBusqueda.aspx

    console.log('[STEP 01] navigate FrmBusqueda.aspx');
    await page.goto(`${BASE_URL}FrmBusqueda.aspx`, { waitUntil: 'domcontentloaded' });
    await waitForAgendaStable(page);

    await page.screenshot({ path: 'evidence/120/P10/step_01_after.png' });
    
    
    
    // [STEP 02] fill pb_step_1 with ""

    console.log('[STEP 02] fill pb_step_1');
    await page.locator("#c_abfCodCliente").scrollIntoViewIfNeeded().catch(() => null);
    await page.locator("#c_abfCodCliente").fill('');
    await page.screenshot({ path: 'evidence/120/P10/step_02_after.png' });
    STEP_BBOXES.push({ step_index: 2, screenshot_path: 'evidence/120/P10/step_02_after.png', target: "pb_step_1", bbox: await page.locator("#c_abfCodCliente").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 03] click pb_step_2

    console.log('[STEP 03] click pb_step_2');
    await page.locator("#c_btnOk").scrollIntoViewIfNeeded().catch(() => null);
    await page.locator("#c_btnOk").click();
    await waitForAgendaStable(page);
    await page.screenshot({ path: 'evidence/120/P10/step_03_after.png' });
    STEP_BBOXES.push({ step_index: 3, screenshot_path: 'evidence/120/P10/step_03_after.png', target: "pb_step_2", bbox: await page.locator("#c_btnOk").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 04] click pb_step_3

    console.log('[STEP 04] click pb_step_3');
    await page.locator("#c_GridPersonas tbody tr:first-child").scrollIntoViewIfNeeded().catch(() => null);
    await page.locator("#c_GridPersonas tbody tr:first-child").click();
    await waitForAgendaStable(page);
    await page.screenshot({ path: 'evidence/120/P10/step_04_after.png' });
    STEP_BBOXES.push({ step_index: 4, screenshot_path: 'evidence/120/P10/step_04_after.png', target: "pb_step_3", bbox: await page.locator("#c_GridPersonas tbody tr:first-child").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 05] click pb_step_4

    console.log('[STEP 05] click pb_step_4');
    await page.locator("#c_GridObligaciones tbody tr:first-child").scrollIntoViewIfNeeded().catch(() => null);
    await page.locator("#c_GridObligaciones tbody tr:first-child").click();
    await waitForAgendaStable(page);
    await page.screenshot({ path: 'evidence/120/P10/step_05_after.png' });
    STEP_BBOXES.push({ step_index: 5, screenshot_path: 'evidence/120/P10/step_05_after.png', target: "pb_step_4", bbox: await page.locator("#c_GridObligaciones tbody tr:first-child").boundingBox().catch(() => null) });
    
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGCANAL"').toContainText('nuevo valor de OGCANAL');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGMEDIOPAGO"').toContainText('nuevo valor de OGMEDIOPAGO');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGDEBAUT_DESC"').toContainText('nuevo valor de OGDEBAUT_DESC');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de DESALDOFAVOR"').toContainText('nuevo valor de DESALDOFAVOR');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGCUOTA"').toContainText('nuevo valor de OGCUOTA');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGMONTOCUOTA"').toContainText('nuevo valor de OGMONTOCUOTA');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGCORREDOR"').toContainText('nuevo valor de OGCORREDOR');
    
    
    
    await expect(page.locator('body'), 'P10: página debe contener "nuevo valor de OGNROCUOTAS"').toContainText('nuevo valor de OGNROCUOTAS');
    
    

    // Final screenshot after all assertions
    await page.screenshot({ path: 'evidence/120/P10/step_final_state.png' }).catch(() => null);
  });

  test.afterEach(async ({ page }) => {
    // afterEach runs AFTER the test body — including after failures.
    // The final screenshot was already taken in the test body; here we only
    // capture evidence if the test crashed before reaching it.
    try {
      await page.screenshot({
        path: 'evidence/120/P10/step_aftereach_state.png',
      });
    } catch (_e) {
      // ignore — page may be closed or navigating
    }

    // ASSERTIONS EVIDENCE — capture actual values for every oracle so
    // uat_assertion_evaluator.py can reconcile expected vs actual without
    // relying on Playwright's pass/fail (which conflates product defects
    // with pipeline defects).
    const captured: any[] = [];
    for (const probe of ORACLE_PROBES) {
      const entry: any = {
        oracle_id: probe.oracle_id,
        target: probe.target,
        tipo: probe.tipo,
        expected: probe.expected,
      };
      try {
        if (probe.selector === null) {
          // Whole-page oracle: capture the body text once (truncated).
          const bodyText = (await page.locator('body').innerText({ timeout: 2000 })) || '';
          entry.actual_text = bodyText.slice(0, 4000);
          entry.visible = true;
        } else if (probe.tipo === 'field_ais_state') {
          // Fase 4: AIS FieldState multi-signal detection.
          // Captures all signals AIS WebForms uses to express ReadOnly/Disabled:
          //   fieldstate attr, disabled, readOnly, aspNetDisabled class,
          //   CSS pointer-events:none, aria-readonly.
          const aisState = await page.evaluate((sel: string) => {
            const el = document.querySelector(sel) as HTMLElement | null;
            if (!el) return null;
            const inp = el as HTMLInputElement;
            const cs = window.getComputedStyle(el);
            return {
              fieldstate: el.getAttribute('fieldstate') || null,
              disabled: inp.disabled === true,
              readonly: inp.readOnly === true,
              has_readonly: el.hasAttribute('readonly'),
              aspnet_disabled: el.classList.contains('aspNetDisabled'),
              css_no_pointer: cs.pointerEvents === 'none',
              aria_readonly: el.getAttribute('aria-readonly') === 'true',
            };
          }, probe.selector).catch(() => null);
          entry.ais_state = aisState;
          if (aisState) {
            const isReadonly = aisState.fieldstate?.toUpperCase() === 'READONLY'
              || aisState.readonly || aisState.has_readonly
              || aisState.css_no_pointer || aisState.aria_readonly;
            const isDisabled = aisState.disabled || aisState.aspnet_disabled;
            entry.state = isReadonly ? 'readonly' : isDisabled ? 'disabled' : 'enabled';
            entry.visible = await page.locator(probe.selector).first().isVisible({ timeout: 2000 }).catch(() => null);
          } else {
            entry.state = null;
            entry.visible = false;
          }
        } else {
          const loc = page.locator(probe.selector);
          // count
          const count = await loc.count();
          entry.count = count;
          if (count === 0) {
            entry.visible = false;
            entry.actual_text = null;
          } else {
            entry.visible = await loc.first().isVisible({ timeout: 2000 });
            // value (form controls)
            try {
              entry.value = await loc.first().inputValue({ timeout: 1000 });
            } catch (_e) { /* not a form control */ }
            // textContent
            try {
              const txt = (await loc.first().innerText({ timeout: 1500 })) || '';
              entry.actual_text = txt.slice(0, 1000);
            } catch (_e) {
              entry.actual_text = null;
            }
            // disabled / state
            try {
              entry.state = (await loc.first().isDisabled({ timeout: 500 })) ? 'disabled' : 'enabled';
            } catch (_e) { /* ignore */ }
          }
        }
      } catch (e: any) {
        entry.capture_error = String(e && e.message ? e.message : e).slice(0, 300);
      }
      captured.push(entry);
    }

    // Persist assertions_<sid>.json. mkdir is safe-recursive; failures here
    // must not break the test runner.
    try {
      const outPath = path.resolve(process.cwd(), ASSERTIONS_OUT_PATH);
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(
        outPath,
        JSON.stringify(
          { scenario_id: 'P10', assertions: captured },
          null, 2,
        ),
        'utf-8',
      );
    } catch (e) {
      console.error('[afterEach] could not persist assertions json:', e);
    }

    // Persist step_bboxes.json for screenshot_annotator.py (Fase 2).
    // Non-fatal: if this fails the pipeline continues without annotations.
    if (STEP_BBOXES.length > 0) {
      try {
        const bboxOutPath = path.resolve(process.cwd(), STEP_BBOXES_OUT_PATH);
        fs.mkdirSync(path.dirname(bboxOutPath), { recursive: true });
        fs.writeFileSync(bboxOutPath, JSON.stringify(STEP_BBOXES, null, 2), 'utf-8');
      } catch (e) {
        console.error('[afterEach] could not persist step_bboxes json:', e);
      }
    }

  });
});