"""Unit tests for selector_discovery.py (B2)."""
import importlib
import sys
import os
import pytest

# Ensure the tool directory is on the path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

import selector_discovery


def test_data_testid_returns_high():
    el = {"data_testid": "btn-buscar", "kind": "button", "role": "button", "label": "Buscar"}
    result = selector_discovery.discover_selector(el)
    assert result["robustness"] == "high"
    assert "btn-buscar" in result["selector"]


def test_stable_asp_id_returns_medium():
    el = {"asp_id": "btnOk", "kind": "button", "role": "button", "label": None, "data_testid": None}
    result = selector_discovery.discover_selector(el)
    assert result["robustness"] == "medium"
    assert "btnOk" in result["selector"]


def test_autogenerated_asp_id_returns_low():
    el = {
        "asp_id": "ctl00_ContentPlaceHolder1_ctl03_btnOk",
        "kind": "button",
        "role": "button",
        "label": None,
        "data_testid": None,
    }
    result = selector_discovery.discover_selector(el)
    assert result["robustness"] == "low"
    assert result.get("warning") == "requires_data_testid_from_dev"


def test_label_only_returns_high():
    el = {"label": "Fecha Desde", "role": "textbox", "kind": "input", "asp_id": None, "data_testid": None}
    result = selector_discovery.discover_selector(el)
    assert result["robustness"] == "high"
    assert "Fecha Desde" in result["selector"]


def test_empty_input_returns_low_without_exception():
    el = {}
    result = selector_discovery.discover_selector(el)
    assert result["robustness"] == "low"
    assert "selector" in result


def test_deterministic_pure_function():
    el = {"label": "Empresa", "role": "combobox", "kind": "select", "asp_id": "ddlEmpresa", "data_testid": None}
    r1 = selector_discovery.discover_selector(el)
    r2 = selector_discovery.discover_selector(el)
    assert r1 == r2
