// ADO-367 P03 — Una búsqueda por Póliza/Obligación con el valor completo (>20 caracteres) retorna el cliente esperado.
// Generated by playwright_test_generator.py v1.1.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/367/scenarios.json --ui-maps cache/ui_maps/ --out evidence/367/tests/
// Screen: FrmBusqueda.aspx


import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';


const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');



// NOTE: AGENDA_WEB_USER / AGENDA_WEB_PASS are used only by playwright/global.setup.ts
// for the one-time login.  Specs restore auth from storageState — no login here.

/**
 * waitForAgendaStable — Wait for AgendaWeb / ASP.NET WebForms to settle.
 *
 * Replaces raw waitForLoadState('load') which misses UpdatePanel async PostBacks.
 * Strategy:
 *   1. Wait for DOM content parsed (domcontentloaded — fast, reliable).
 *   2. Wait for ASP.NET PageRequestManager async PostBack to finish (UpdatePanel).
 *   3. Fail-safe: if Sys is not available, resolve immediately (static pages).
 */
async function waitForAgendaStable(page: any, timeout = 10_000): Promise<void> {
  await page.waitForLoadState('domcontentloaded').catch(() => null);
  await page.waitForFunction(
    () => {
      try {
        const prm = (window as any).Sys?.WebForms?.PageRequestManager?.getInstance?.();
        return !prm || !prm.get_isInAsyncPostBack();
      } catch (_) {
        return true;  // Sys not available — page is stable
      }
    },
    null,
    { timeout },
  ).catch(() => null);  // Never fail the test on this wait — it's best-effort
}

// ORACLE_PROBES — generated from scenario.oraculos × ui_map.
// Consumed by the test.afterEach hook to write
// evidence/<ticket>/<sid>/assertions_<sid>.json with the actual values
// captured from the live DOM, regardless of whether the test passed,
// failed, or threw. uat_assertion_evaluator.py reads this file as the
// primary source of truth for expected/actual reconciliation; without
// it every oracle would default to status=review.
type OracleProbe = {
  oracle_id: number;
  target: string;
  tipo: string;
  expected: string | number | null;
  selector: string | null;  // CSS-ish; null for whole-page oracles
};
const ORACLE_PROBES: OracleProbe[] = [

  {
    oracle_id: 0,
    target: "grid_c_gridpersonas",
    tipo: "page_contains_text",
    expected: "Cliente Esperado",
    selector: null
  },

];
const ASSERTIONS_OUT_PATH = 'evidence/367/P03/assertions_P03.json';

// STEP_BBOXES — accumulates bounding boxes of interacted elements per step.
// Written by test.afterEach to evidence/<ticket>/<sid>/step_bboxes.json and
// consumed by screenshot_annotator.py (Fase 2) to draw red boxes on screenshots.
type StepBboxEntry = {
  step_index: number;
  screenshot_path: string;
  target: string;
  bbox: { x: number; y: number; width: number; height: number } | null;
};
const STEP_BBOXES: StepBboxEntry[] = [];
const STEP_BBOXES_OUT_PATH = 'evidence/367/P03/step_bboxes.json';


// TARGET_SCREEN — final screen the scenario must reach after all navigation steps.
// ENTRY_SCREEN — first screen the spec lands on (entrypoint of the human path).
// For session-dependent target screens (e.g. FrmDetalleClie.aspx), ENTRY_SCREEN
// is the playbook's entry_screen (e.g. FrmBusqueda.aspx) and the action_steps
// walk from there to TARGET_SCREEN. When no playbook is involved (entrypoint
// screens like FrmAgenda.aspx), ENTRY_SCREEN == TARGET_SCREEN.
const TARGET_SCREEN = 'FrmBusqueda.aspx';
const ENTRY_SCREEN = 'FrmBusqueda.aspx';

test.describe('ADO-367 | P03 — Una búsqueda por Póliza/Obligación con el valor completo (>20 caracteres) retorna el cliente esperado.', () => {

  test.beforeEach(async ({ page }) => {
    // Auth is restored from storageState (written by playwright/global.setup.ts).
    // NO login here — the session is already established.
    // beforeEach navigates to the ENTRY screen (NOT the target screen directly).
    // For session-dependent targets, hitting them with page.goto crashes the
    // ASP.NET app pool. The action_steps below walk the human path from entry.
    await page.goto(`${BASE_URL}${ENTRY_SCREEN}`, { waitUntil: 'domcontentloaded', timeout: 20_000 });
    await waitForAgendaStable(page);
    const beforeEachUrl = page.url().toLowerCase();
    if (beforeEachUrl.includes('frmlogin')) {
      throw new Error(
        `[${ENTRY_SCREEN}] Session expired before test start. ` +
        'Re-run the pipeline to refresh auth (global.setup.ts). ' +
        'DO NOT re-run login in specs.',
      );
    }
    // Verify we actually reached the entry screen (not a redirect to another page).
    if (!beforeEachUrl.includes(ENTRY_SCREEN.toLowerCase().replace('.aspx', ''))) {
      throw new Error(
        `[WRONG_SCREEN] Expected to reach entry ${ENTRY_SCREEN} but landed on: ${page.url()}. ` +
        'Verify the playbook entry_screen and navigation contract.',
      );
    }
  });

  test('p03 una_búsqueda_por_póliza/obligación_con_el_valor_completo_(>2', async ({ page }) => {
    // DATA: Póliza='VM12-P-1816961389-60'

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    
    // - El usuario debe estar autenticado en AgendaWeb.
    
    // - El usuario debe tener acceso a la pantalla de Búsqueda de Clientes.
    

    // ── Exception & network listener setup ──────────────────────────────────
    // stepRef permite a los listeners pasivos (response / pageerror / console)
    // registrar en qué step de acción ocurrió el evento, sin pasar `page` al
    // cierre del listener.


    // SETUP — beforeEach already navigated to ENTRY_SCREEN. Re-affirm and screenshot
    // ONLY if we somehow drifted off it (e.g. an UpdatePanel redirected us). Hitting
    // page.goto on a session-dependent TARGET_SCREEN here would crash the app pool,
    // so we navigate to ENTRY_SCREEN, not pantalla.
    {
      const currentUrl0 = page.url().toLowerCase();
      if (!currentUrl0.includes(ENTRY_SCREEN.toLowerCase().replace('.aspx', ''))) {
        await page.goto(`${BASE_URL}${ENTRY_SCREEN}`, { waitUntil: 'domcontentloaded' });
        await waitForAgendaStable(page);
      }
    }

    await page.screenshot({ path: 'evidence/367/P03/step_00_setup.png' });

    // ENTRY SCREEN VALIDATION — fail fast if we're not on the expected entrypoint.
    // The action_steps below are responsible for walking from ENTRY_SCREEN to TARGET_SCREEN.
    {
      const setupUrl = page.url().toLowerCase();
      if (setupUrl.includes('frmlogin')) {
        throw new Error(
          `[BLOCKED_LOGIN_FAILED] Navigation to ${ENTRY_SCREEN} redirected to login page. ` +
          'Session is invalid. Re-run the pipeline (do NOT add login logic to specs).',
        );
      }
      if (!setupUrl.includes(ENTRY_SCREEN.toLowerCase().replace('.aspx', ''))) {
        throw new Error(
          `[BLOCKED_WRONG_SCREEN] Expected entrypoint: ${ENTRY_SCREEN} — Got: ${page.url()}. ` +
          'Check the playbook entry_screen and navigation contract.',
        );
      }
    }

    // Expand "Búsqueda Avanzada" panel only when needed.
    // Some Agenda layouts don't expose data-toggle attrs, so use resilient fallback.
    const advancedPanel = page.locator('#c_pnlBusqueda');
    const firstFilter = page.locator('#c_ddlDebitoAuto, #c_abfCorredor, #c_abfNombreCliente, #c_abfRUC, #c_btnOk');
    let filtersReady = await firstFilter.first().isVisible().catch(() => false);
    if (!filtersReady) {
      const toggleByHeader = page.locator('.collapsible-header:has-text("Búsqueda Avanzada"), li:has-text("Búsqueda Avanzada") .collapsible-header').first();
      const toggleByData = page.locator('[data-toggle="collapse"][href="#c_pnlBusqueda"], [data-toggle="collapse"][data-target="#c_pnlBusqueda"]').first();
      const toggleByText = page.getByText('Búsqueda Avanzada', { exact: false }).first();

      if (await toggleByHeader.count()) {
        await toggleByHeader.scrollIntoViewIfNeeded();
        await toggleByHeader.click({ timeout: 5000 });
      } else if (await toggleByData.count()) {
        await toggleByData.scrollIntoViewIfNeeded();
        await toggleByData.click({ timeout: 5000 });
      } else if (await toggleByText.count()) {
        await toggleByText.click({ timeout: 5000 });
      }

      if (await advancedPanel.count()) {
        await advancedPanel.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
      }
      filtersReady = await firstFilter.first().isVisible().catch(() => false);

      // Last-resort fallback for legacy WebForms layouts where the toggle
      // exists but does not update aria/visibility attributes consistently.
      if (!filtersReady && await advancedPanel.count()) {
        await page.evaluate(() => {
          const pnl = document.querySelector('#c_pnlBusqueda') as HTMLElement | null;
          if (pnl) {
            pnl.style.display = 'block';
            pnl.classList.add('active');
          }
        });
        filtersReady = await firstFilter.first().isVisible().catch(() => false);
      }
    }
    console.log('Advanced filters ready:', filtersReady);
    await page.screenshot({ path: 'screenshots/P03_panel_expanded.png' });

    // ACTION
    
    
    // [STEP 01] navigate to FrmBusqueda.aspx

    console.log('[STEP 01] navigate FrmBusqueda.aspx');
    await page.goto(`${BASE_URL}FrmBusqueda.aspx`, { waitUntil: 'domcontentloaded' });
    await waitForAgendaStable(page);

    await page.screenshot({ path: 'evidence/367/P03/step_01_after.png' });
    
    
    
    // [STEP 02] wait visible pb_step_1
    await expect(page.locator('#c_UpdatePanelObligaciones')).toBeVisible({ timeout: 15000 });
    
    
    
    // [STEP 03] wait visible pb_step_2
    await expect(page.locator('#c_UpdatePanelObligaciones')).toBeVisible({ timeout: 15000 });
    
    

    // TARGET ARRIVAL ASSERTION — after walking the human path the URL must contain
    // TARGET_SCREEN. This decouples the entry-vs-target navigation: tests fail
    // here with a clear error if the playbook steps did not reach destination,
    // instead of mis-categorising a navigation defect as a product assertion failure.
    {
      const finalNavUrl = page.url().toLowerCase();
      const targetNeedle = TARGET_SCREEN.toLowerCase().replace('.aspx', '');
      if (finalNavUrl.includes('frmlogin')) {
        throw new Error(
          `[ARRIVAL_LOGIN_REDIRECT] Walking from ${ENTRY_SCREEN} to ${TARGET_SCREEN} ` +
          `was redirected to login. Session expired mid-test or playbook broke the session.`,
        );
      }
      if (TARGET_SCREEN !== ENTRY_SCREEN && !finalNavUrl.includes(targetNeedle)) {
        throw new Error(
          `[ARRIVAL_WRONG_SCREEN] After action_steps expected ${TARGET_SCREEN} ` +
          `— Got: ${page.url()}. Likely cause: a playbook step failed to navigate ` +
          `or the playbook is missing the final transition.`,
        );
      }
    }

    // ASSERTIONS
    
    
    await expect(page.locator('body'), 'P03: página debe contener "Cliente Esperado"').toContainText('Cliente Esperado');
    
    

    // Final screenshot after all assertions
    await page.screenshot({ path: 'evidence/367/P03/step_final_state.png' }).catch(() => null);
  });

  test.afterEach(async ({ page }) => {
    // afterEach runs AFTER the test body — including after failures.
    // The final screenshot was already taken in the test body; here we only
    // capture evidence if the test crashed before reaching it.
    try {
      await page.screenshot({
        path: 'evidence/367/P03/step_aftereach_state.png',
      });
    } catch (_e) {
      // ignore — page may be closed or navigating
    }

    // ASSERTIONS EVIDENCE — capture actual values for every oracle so
    // uat_assertion_evaluator.py can reconcile expected vs actual without
    // relying on Playwright's pass/fail (which conflates product defects
    // with pipeline defects).
    const captured: any[] = [];
    for (const probe of ORACLE_PROBES) {
      const entry: any = {
        oracle_id: probe.oracle_id,
        target: probe.target,
        tipo: probe.tipo,
        expected: probe.expected,
      };
      try {
        if (probe.selector === null) {
          // Whole-page oracle: capture the body text once (truncated).
          const bodyText = (await page.locator('body').innerText({ timeout: 2000 })) || '';
          entry.actual_text = bodyText.slice(0, 4000);
          entry.visible = true;
        } else if (probe.tipo === 'field_ais_state') {
          // Fase 4: AIS FieldState multi-signal detection.
          // Captures all signals AIS WebForms uses to express ReadOnly/Disabled:
          //   fieldstate attr, disabled, readOnly, aspNetDisabled class,
          //   CSS pointer-events:none, aria-readonly.
          const aisState = await page.evaluate((sel: string) => {
            const el = document.querySelector(sel) as HTMLElement | null;
            if (!el) return null;
            const inp = el as HTMLInputElement;
            const cs = window.getComputedStyle(el);
            return {
              fieldstate: el.getAttribute('fieldstate') || null,
              disabled: inp.disabled === true,
              readonly: inp.readOnly === true,
              has_readonly: el.hasAttribute('readonly'),
              aspnet_disabled: el.classList.contains('aspNetDisabled'),
              css_no_pointer: cs.pointerEvents === 'none',
              aria_readonly: el.getAttribute('aria-readonly') === 'true',
            };
          }, probe.selector).catch(() => null);
          entry.ais_state = aisState;
          if (aisState) {
            const isReadonly = aisState.fieldstate?.toUpperCase() === 'READONLY'
              || aisState.readonly || aisState.has_readonly
              || aisState.css_no_pointer || aisState.aria_readonly;
            const isDisabled = aisState.disabled || aisState.aspnet_disabled;
            entry.state = isReadonly ? 'readonly' : isDisabled ? 'disabled' : 'enabled';
            entry.visible = await page.locator(probe.selector).first().isVisible({ timeout: 2000 }).catch(() => null);
          } else {
            entry.state = null;
            entry.visible = false;
          }
        } else {
          const loc = page.locator(probe.selector);
          // count
          const count = await loc.count();
          entry.count = count;
          if (count === 0) {
            entry.visible = false;
            entry.actual_text = null;
          } else {
            entry.visible = await loc.first().isVisible({ timeout: 2000 });
            // value (form controls)
            try {
              entry.value = await loc.first().inputValue({ timeout: 1000 });
            } catch (_e) { /* not a form control */ }
            // textContent
            try {
              const txt = (await loc.first().innerText({ timeout: 1500 })) || '';
              entry.actual_text = txt.slice(0, 1000);
            } catch (_e) {
              entry.actual_text = null;
            }
            // disabled / state
            try {
              entry.state = (await loc.first().isDisabled({ timeout: 500 })) ? 'disabled' : 'enabled';
            } catch (_e) { /* ignore */ }
          }
        }
      } catch (e: any) {
        entry.capture_error = String(e && e.message ? e.message : e).slice(0, 300);
      }
      captured.push(entry);
    }

    // Persist assertions_<sid>.json. mkdir is safe-recursive; failures here
    // must not break the test runner.
    try {
      const outPath = path.resolve(process.cwd(), ASSERTIONS_OUT_PATH);
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(
        outPath,
        JSON.stringify(
          { scenario_id: 'P03', assertions: captured },
          null, 2,
        ),
        'utf-8',
      );
    } catch (e) {
      console.error('[afterEach] could not persist assertions json:', e);
    }

    // Persist step_bboxes.json for screenshot_annotator.py (Fase 2).
    // Non-fatal: if this fails the pipeline continues without annotations.
    if (STEP_BBOXES.length > 0) {
      try {
        const bboxOutPath = path.resolve(process.cwd(), STEP_BBOXES_OUT_PATH);
        fs.mkdirSync(path.dirname(bboxOutPath), { recursive: true });
        fs.writeFileSync(bboxOutPath, JSON.stringify(STEP_BBOXES, null, 2), 'utf-8');
      } catch (e) {
        console.error('[afterEach] could not persist step_bboxes json:', e);
      }
    }

  });
});