import { create } from "zustand";
export const useWorkbench = create((set) => ({
    activeTicketId: null,
    activeAgentType: null,
    activeExecutionId: null,
    codexConsoleExecutionId: null,
    codexConsoleMinimized: false,
    blocks: [],
    runningExecutionId: null,
    modelOverride: null,
    systemPromptOverride: null,
    vsCodeAgent: null,
    activeProject: null,
    pinnedAgents: [],
    agentWorkflows: {},
    teamLoading: false,
    getAgentsError: null,
    agentRuntime: "github_copilot",
    // P1.1 ChatDrawer state
    chatDrawerOpen: false,
    chatDrawerModel: null,
    chatDrawerTicketId: null,
    setActiveTicket: (id) => set({ activeTicketId: id, activeExecutionId: null, blocks: [] }),
    setActiveAgent: (t) => set({
        activeAgentType: t,
        activeExecutionId: null,
        systemPromptOverride: null,
        vsCodeAgent: null,
    }),
    setActiveExecution: (id) => set({ activeExecutionId: id }),
    setCodexConsoleExecution: (id, minimized = false) => set({
        codexConsoleExecutionId: id,
        codexConsoleMinimized: id == null ? false : minimized,
    }),
    setCodexConsoleMinimized: (value) => set({ codexConsoleMinimized: value }),
    setBlocks: (b) => set({ blocks: b }),
    patchBlock: (id, patch) => set((s) => ({
        blocks: s.blocks.map((b) => (b.id === id ? { ...b, ...patch } : b)),
    })),
    removeBlock: (id) => set((s) => ({ blocks: s.blocks.filter((b) => b.id !== id) })),
    setRunningExecution: (id) => set({ runningExecutionId: id }),
    setModelOverride: (m) => set({ modelOverride: m }),
    setSystemPromptOverride: (sp) => set({ systemPromptOverride: sp }),
    setVsCodeAgent: (a) => set({
        vsCodeAgent: a,
        activeAgentType: a ? "custom" : null,
        activeExecutionId: null,
        systemPromptOverride: a?.system_prompt ?? null,
    }),
    setActiveProject: (p) => set({ activeProject: p }),
    setPinnedAgents: (agents) => set({ pinnedAgents: agents }),
    setAgentWorkflows: (wf) => set({ agentWorkflows: wf }),
    setTeamLoading: (loading) => set({ teamLoading: loading }),
    setGetAgentsError: (err) => set({ getAgentsError: err }),
    setAgentRuntime: (r) => set({ agentRuntime: r }),
    // P1.1 ChatDrawer actions
    setChatDrawerOpen: (open) => set({ chatDrawerOpen: open }),
    setChatDrawerModel: (model) => set({ chatDrawerModel: model }),
    setChatDrawerTicketId: (id) => set({ chatDrawerTicketId: id }),
}));
