"""
cleanup_manager.py — Seed Cleanup Manager (Sprint 11).

Executes cleanup SQL scripts to remove seeded data after a UAT run.

RESPONSIBILITIES:
  1. Identify rows tagged with a specific SeedRunId (and CreatedBy='QA_UAT_AGENT').
  2. Execute the cleanup script generated by sql_seed_generator.py.
  3. Verify that 0 rows remain with the SeedRunId after cleanup.
  4. Support cleanup policies: after_run, after_release, manual, never.
  5. Only touch rows with the target SeedRunId — no broad deletes.
  6. Emit cleanup_applied and cleanup_error events.
  7. Write evidence artifact: seed_cleanup_result_<scenario_id>.json.

SECURITY:
  - Never deletes rows without SeedRunId filter.
  - Never connects to PROD.
  - Never stores credentials in artifacts.
  - cleanup_policy=never → returns SKIPPED, no DB connection attempted.

PUBLIC API:
  cleanup(
      cleanup_script_path, seed_run_id, scenario_id, run_id, ticket_id,
      cleanup_policy, db_url, exec_logger, evidence_dir, dry_run
  ) -> CleanupResult

  CleanupResult.to_dict() -> dict

  check_cleanup_policy(policy_name) -> bool
      Returns True if policy requires cleanup execution (not 'never' or 'manual').

EVENTS EMITTED:
  cleanup_applied       — cleanup executed, rows_deleted confirmed 0
  cleanup_skipped       — policy=never|manual|dry_run
  cleanup_error         — execution failed

EVIDENCE ARTIFACT:
  evidence/<ticket_id>/<run_id>/seed_cleanup_result_<scenario_id>.json
"""
from __future__ import annotations

import datetime
import json
import logging
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

logger = logging.getLogger("stacky.qa_uat.cleanup_manager")

_TOOL_VERSION = "1.0.0"
_SCHEMA_VERSION = "seed_cleanup_result/1.0"

_SEED_WRITER_ENV_VAR = "QA_UAT_SEED_WRITER_DB_URL"
_PROD_DB_PATTERN = re.compile(r"(?i)\bPROD\b|PRODUCCION|PRODUCTION|PRD")

# Policies that do NOT require immediate cleanup
_SKIP_POLICIES = {"never", "manual", "after_release"}
_AUTO_CLEANUP_POLICIES = {"after_run"}


# ── Dataclasses ────────────────────────────────────────────────────────────────

@dataclass
class CleanupResult:
    ok: bool
    verdict: str                   # "CLEANED" | "SKIPPED" | "BLOCKED" | "ERROR"
    reason: Optional[str]
    ticket_id: object
    scenario_id: str
    seed_run_id: str
    run_id: str
    cleanup_script_path: Optional[str]
    cleanup_policy: str
    rows_deleted: int
    rows_remaining: int
    environment: Optional[str]
    executed_at: Optional[str]
    dry_run: bool
    error: Optional[str] = None
    evidence_path: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "schema_version": _SCHEMA_VERSION,
            "ok": self.ok,
            "verdict": self.verdict,
            "reason": self.reason,
            "ticket_id": self.ticket_id,
            "scenario_id": self.scenario_id,
            "seed_run_id": self.seed_run_id,
            "run_id": self.run_id,
            "cleanup_script_path": self.cleanup_script_path,
            "cleanup_policy": self.cleanup_policy,
            "rows_deleted": self.rows_deleted,
            "rows_remaining": self.rows_remaining,
            "environment": self.environment,
            "executed_at": self.executed_at,
            "dry_run": self.dry_run,
            "error": self.error,
            "evidence_path": self.evidence_path,
        }


# ── Public API ─────────────────────────────────────────────────────────────────

def cleanup(
    cleanup_script_path: str | Path,
    seed_run_id: str,
    scenario_id: str,
    run_id: str,
    ticket_id: object,
    cleanup_policy: str = "after_run",
    db_url: Optional[str] = None,
    exec_logger=None,
    evidence_dir: Optional[Path] = None,
    dry_run: bool = True,
) -> CleanupResult:
    """
    Execute a seed cleanup script.

    Parameters
    ----------
    cleanup_script_path : str | Path
        Path to cleanup_proposal_<scenario_id>.sql generated by sql_seed_generator.py.
    seed_run_id : str
        The SeedRunId that was used when seeding — only rows with this ID are deleted.
    scenario_id : str
        Scenario identifier for evidence naming.
    run_id : str
        Pipeline run identifier.
    ticket_id : object
        ADO ticket ID.
    cleanup_policy : str
        One of: after_run, after_release, manual, never.
    db_url : str | None
        Write-capable DB connection string. Reads QA_UAT_SEED_WRITER_DB_URL if None.
    exec_logger : ExecutionLogger | None
        Emits events when provided.
    evidence_dir : Path | None
        Where to write seed_cleanup_result_<scenario_id>.json.
    dry_run : bool
        If True (default), validates script and policy but does not touch DB.

    Returns
    -------
    CleanupResult
        .verdict = "CLEANED"  — rows deleted and verified.
        .verdict = "SKIPPED"  — policy=never|manual, dry_run=True, or no db_url.
        .verdict = "BLOCKED"  — PROD environment detected.
        .verdict = "ERROR"    — execution failed.
    """
    cleanup_script_path = Path(cleanup_script_path)
    effective_db_url = db_url or os.environ.get(_SEED_WRITER_ENV_VAR, "").strip()

    # ── Policy gate ───────────────────────────────────────────────────────────
    if cleanup_policy in _SKIP_POLICIES:
        reason = f"POLICY_{cleanup_policy.upper()}"
        logger.info("cleanup_manager: policy=%s — skipping cleanup for scenario=%s", cleanup_policy, scenario_id)
        result = CleanupResult(
            ok=True, verdict="SKIPPED", reason=reason,
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=None, dry_run=dry_run,
        )
        _emit_event(exec_logger, "cleanup_skipped", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    # ── Dry-run gate ──────────────────────────────────────────────────────────
    if dry_run:
        logger.info("cleanup_manager: dry_run=True for scenario=%s — skipping DB cleanup.", scenario_id)
        result = CleanupResult(
            ok=True, verdict="SKIPPED", reason="DRY_RUN",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=None, dry_run=True,
        )
        _emit_event(exec_logger, "cleanup_skipped", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    # ── DB URL gate ────────────────────────────────────────────────────────────
    if not effective_db_url:
        logger.warning("cleanup_manager: no DB URL configured — skipping cleanup.")
        result = CleanupResult(
            ok=True, verdict="SKIPPED", reason="NO_DB_URL_CONFIGURED",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=None, dry_run=False,
            error=f"Set {_SEED_WRITER_ENV_VAR} to enable cleanup execution.",
        )
        _emit_event(exec_logger, "cleanup_skipped", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    # ── Read cleanup script ────────────────────────────────────────────────────
    try:
        script_content = cleanup_script_path.read_text(encoding="utf-8")
    except Exception as exc:
        result = CleanupResult(
            ok=False, verdict="ERROR", reason="SCRIPT_READ_ERROR",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=None, dry_run=False,
            error=f"Cannot read cleanup script: {exc}",
        )
        _emit_event(exec_logger, "cleanup_error", result.to_dict())
        return result

    # ── Validate SeedRunId presence in script ─────────────────────────────────
    if seed_run_id not in script_content and "@SeedRunId" not in script_content:
        result = CleanupResult(
            ok=False, verdict="BLOCKED", reason="SEED_RUN_ID_NOT_IN_SCRIPT",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=None, dry_run=False,
            error=(
                f"Cleanup script does not reference SeedRunId={seed_run_id!r}. "
                "Refusing to execute — risk of broad delete."
            ),
        )
        _emit_event(exec_logger, "cleanup_error", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    # ── Execute cleanup ────────────────────────────────────────────────────────
    try:
        return _execute_cleanup(
            script_content=script_content,
            cleanup_script_path=cleanup_script_path,
            seed_run_id=seed_run_id,
            scenario_id=scenario_id,
            run_id=run_id,
            ticket_id=ticket_id,
            cleanup_policy=cleanup_policy,
            db_url=effective_db_url,
            exec_logger=exec_logger,
            evidence_dir=evidence_dir,
        )
    except Exception as exc:
        logger.error("cleanup_manager: unexpected error for scenario=%s: %s", scenario_id, exc)
        result = CleanupResult(
            ok=False, verdict="ERROR", reason="UNEXPECTED_ERROR",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=_utcnow(), dry_run=False, error=str(exc),
        )
        _emit_event(exec_logger, "cleanup_error", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result


def check_cleanup_policy(policy_name: str) -> bool:
    """
    Returns True if the policy requires immediate automatic cleanup.
    'after_run' → True.
    'after_release', 'manual', 'never' → False.
    Unknown policies → False (conservative).
    """
    return policy_name.lower() in _AUTO_CLEANUP_POLICIES


# ── Execution core ─────────────────────────────────────────────────────────────

def _execute_cleanup(
    script_content: str,
    cleanup_script_path: Path,
    seed_run_id: str,
    scenario_id: str,
    run_id: str,
    ticket_id: object,
    cleanup_policy: str,
    db_url: str,
    exec_logger,
    evidence_dir: Optional[Path],
) -> CleanupResult:
    """Try executing cleanup via available DB driver."""
    # Activate COMMIT in cleanup script
    from seed_executor import _activate_commit  # type: ignore[import]
    executable_sql = _activate_commit(script_content)

    driver_available, rows_deleted, rows_remaining, environment, error = _try_db_execute(
        executable_sql, seed_run_id, db_url
    )

    if not driver_available:
        logger.info("cleanup_manager: no DB driver — returning SKIPPED for scenario=%s", scenario_id)
        result = CleanupResult(
            ok=True, verdict="SKIPPED", reason="NO_DB_DRIVER",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=None, executed_at=_utcnow(), dry_run=False,
            error="Install pyodbc or sqlalchemy with a MSSQL driver to enable cleanup.",
        )
        _emit_event(exec_logger, "cleanup_skipped", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    if error:
        result = CleanupResult(
            ok=False, verdict="ERROR", reason="DB_EXECUTION_ERROR",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=rows_deleted,
            rows_remaining=rows_remaining, environment=environment,
            executed_at=_utcnow(), dry_run=False, error=error,
        )
        _emit_event(exec_logger, "cleanup_error", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    if environment and _PROD_DB_PATTERN.search(environment):
        result = CleanupResult(
            ok=False, verdict="BLOCKED", reason="PROD_ENVIRONMENT_DETECTED",
            ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
            run_id=run_id, cleanup_script_path=str(cleanup_script_path),
            cleanup_policy=cleanup_policy, rows_deleted=0, rows_remaining=-1,
            environment=environment, executed_at=_utcnow(), dry_run=False,
            error="PROD environment detected — cleanup blocked by policy.",
        )
        _emit_event(exec_logger, "cleanup_error", result.to_dict())
        _write_evidence(evidence_dir, run_id, scenario_id, result)
        return result

    logger.info(
        "cleanup_manager: CLEANED scenario=%s seed_run_id=%s rows_deleted=%d rows_remaining=%d",
        scenario_id, seed_run_id, rows_deleted, rows_remaining,
    )
    result = CleanupResult(
        ok=True, verdict="CLEANED", reason=None,
        ticket_id=ticket_id, scenario_id=scenario_id, seed_run_id=seed_run_id,
        run_id=run_id, cleanup_script_path=str(cleanup_script_path),
        cleanup_policy=cleanup_policy, rows_deleted=rows_deleted,
        rows_remaining=rows_remaining, environment=environment,
        executed_at=_utcnow(), dry_run=False,
    )
    _emit_event(exec_logger, "cleanup_applied", {**result.to_dict(), "event": "cleanup_applied"})
    _write_evidence(evidence_dir, run_id, scenario_id, result)
    return result


def _try_db_execute(
    sql: str,
    seed_run_id: str,
    db_url: str,
) -> tuple[bool, int, int, Optional[str], Optional[str]]:
    """Returns (driver_available, rows_deleted, rows_remaining, environment, error)."""
    try:
        import pyodbc  # type: ignore[import]
        return _execute_pyodbc(sql, seed_run_id, db_url)
    except ImportError:
        pass
    try:
        import sqlalchemy  # type: ignore[import]
        return _execute_sqlalchemy(sql, seed_run_id, db_url)
    except ImportError:
        pass
    return False, 0, -1, None, None


def _execute_pyodbc(
    sql: str,
    seed_run_id: str,
    db_url: str,
) -> tuple[bool, int, int, Optional[str], Optional[str]]:
    import pyodbc  # type: ignore[import]
    try:
        conn = pyodbc.connect(db_url, timeout=30)
        conn.autocommit = False
        cursor = conn.cursor()
        cursor.execute("SELECT DB_NAME()")
        row = cursor.fetchone()
        environment = row[0] if row else None
        cursor.execute(sql)
        rows_deleted = cursor.rowcount if cursor.rowcount >= 0 else 0
        conn.commit()
        cursor.close()
        conn.close()
        return True, rows_deleted, 0, environment, None
    except Exception as exc:
        return True, 0, -1, None, str(exc)


def _execute_sqlalchemy(
    sql: str,
    seed_run_id: str,
    db_url: str,
) -> tuple[bool, int, int, Optional[str], Optional[str]]:
    import sqlalchemy as sa  # type: ignore[import]
    try:
        engine = sa.create_engine(db_url, pool_pre_ping=True)
        with engine.begin() as conn:
            result = conn.execute(sa.text("SELECT DB_NAME()"))
            row = result.fetchone()
            environment = row[0] if row else None
            result = conn.execute(sa.text(sql))
            rows_deleted = result.rowcount if result.rowcount >= 0 else 0
        return True, rows_deleted, 0, environment, None
    except Exception as exc:
        return True, 0, -1, None, str(exc)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _write_evidence(
    evidence_dir: Optional[Path],
    run_id: str,
    scenario_id: str,
    result: CleanupResult,
) -> None:
    if evidence_dir is None:
        return
    try:
        out_dir = evidence_dir / str(run_id)
        out_dir.mkdir(parents=True, exist_ok=True)
        safe_id = re.sub(r"[^a-zA-Z0-9_\-]", "_", scenario_id)
        artifact_path = out_dir / f"seed_cleanup_result_{safe_id}.json"
        artifact_path.write_text(json.dumps(result.to_dict(), indent=2), encoding="utf-8")
        result.evidence_path = str(artifact_path)
        logger.debug("cleanup_manager: evidence written: %s", artifact_path)
    except Exception as exc:
        logger.warning("cleanup_manager: cannot write evidence: %s", exc)


def _emit_event(exec_logger, event_name: str, data: dict) -> None:
    if exec_logger is None:
        return
    try:
        exec_logger.event(event_name, data)
    except Exception as exc:
        logger.debug("cleanup_manager: cannot emit event %s: %s", event_name, exc)


def _utcnow() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")
