// playwright.config.ts — generated by playwright_config_writer.py (Sprint 5.1)
// DO NOT EDIT MANUALLY. Re-generate via playwright_config_writer.generate_config().
// All timeout values are read from environment variables at runtime — never hardcoded.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  globalSetup: './playwright/global.setup.ts',
  timeout: Number(process.env.QA_UAT_TEST_TIMEOUT_MS ?? 120000),
  expect: {
    timeout: Number(process.env.QA_UAT_EXPECT_TIMEOUT_MS ?? 10000),
  },
  retries: Number(process.env.QA_UAT_RETRIES ?? 1),
  workers: Number(process.env.QA_UAT_WORKERS ?? 1),
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['junit', { outputFile: 'reports/junit.xml' }],
    ['json', { outputFile: 'reports/playwright-results.json' }],
    ['list'],
  ],
  use: {
    trace: (process.env.QA_UAT_TRACE ?? 'on-first-retry') as 'on-first-retry' | 'always' | 'off' | 'retain-on-failure',
    screenshot: (process.env.QA_UAT_SCREENSHOT ?? 'only-on-failure') as 'only-on-failure' | 'always' | 'off',
    video: (process.env.QA_UAT_VIDEO ?? 'retain-on-failure') as 'retain-on-failure' | 'always' | 'off',
    headless: process.env.QA_UAT_HEADED !== 'true',
    actionTimeout: Number(process.env.QA_UAT_ACTION_TIMEOUT_MS ?? 15000),
    navigationTimeout: Number(process.env.QA_UAT_NAV_TIMEOUT_MS ?? 30000),
    storageState: '.auth/agenda.json',
  },
});
