"""
playwright_config_writer.py — Sprint 5.1: Generate playwright.config.ts from env vars.

PURPOSE
-------
Generate a canonical playwright.config.ts in the QA UAT Agent tool directory
from environment variables.  No timeout is hardcoded — all values are read
from env vars with safe defaults.

ENV VARS SUPPORTED
------------------
QA_UAT_TEST_TIMEOUT_MS    — per-test timeout (default: 60000)
QA_UAT_EXPECT_TIMEOUT_MS  — expect assertion timeout (default: 10000)
QA_UAT_ACTION_TIMEOUT_MS  — locator action timeout (default: 15000)
QA_UAT_NAV_TIMEOUT_MS     — page.goto / waitForNavigation timeout (default: 30000)
QA_UAT_GRID_TIMEOUT_MS    — grid visibility precheck timeout (default: 5000)
QA_UAT_RETRIES            — number of test retries on failure (default: 1)
QA_UAT_WORKERS            — parallel workers (default: 1)
QA_UAT_TRACE              — trace mode: on-first-retry | always | off (default: on-first-retry)
QA_UAT_SCREENSHOT         — screenshot mode: only-on-failure | always | off (default: only-on-failure)
QA_UAT_VIDEO              — video mode: retain-on-failure | always | off (default: retain-on-failure)
QA_UAT_HEADED             — "true" to run headed (default: false → headless)

OUTPUT
------
Writes playwright.config.ts to `output_dir` (default: directory of this file).
Returns the absolute path of the written config as a string.

RULE
----
No generated spec or helper may hardcode timeouts.
All timeout values in generated TypeScript must read from process.env.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

logger = logging.getLogger("stacky.qa_uat.playwright_config_writer")

_TOOL_VERSION = "1.0.0"

# Env var names and their default values (as strings matching TypeScript expectations)
_ENV_DEFAULTS: dict[str, str] = {
    "QA_UAT_TEST_TIMEOUT_MS":    "60000",
    "QA_UAT_EXPECT_TIMEOUT_MS":  "10000",
    "QA_UAT_ACTION_TIMEOUT_MS":  "15000",
    "QA_UAT_NAV_TIMEOUT_MS":     "30000",
    "QA_UAT_GRID_TIMEOUT_MS":    "5000",
    "QA_UAT_RETRIES":            "1",
    "QA_UAT_WORKERS":            "1",
    "QA_UAT_TRACE":              "on-first-retry",
    "QA_UAT_SCREENSHOT":         "only-on-failure",
    "QA_UAT_VIDEO":              "retain-on-failure",
    "QA_UAT_HEADED":             "false",
}

# Valid enum values for string options
_VALID_TRACE       = {"on-first-retry", "always", "off", "retain-on-failure"}
_VALID_SCREENSHOT  = {"only-on-failure", "always", "off"}
_VALID_VIDEO       = {"retain-on-failure", "always", "off"}

# TypeScript config template — no hardcoded timeout values.
# All numeric values come from process.env at runtime in the Node.js process.
_CONFIG_TEMPLATE = """\
// playwright.config.ts — generated by playwright_config_writer.py (Sprint 5.1)
// DO NOT EDIT MANUALLY. Re-generate via playwright_config_writer.generate_config().
// All timeout values are read from environment variables at runtime — never hardcoded.
import {{ defineConfig }} from '@playwright/test';

export default defineConfig({{
  globalSetup: './playwright/global.setup.ts',
  timeout: Number(process.env.QA_UAT_TEST_TIMEOUT_MS ?? {QA_UAT_TEST_TIMEOUT_MS}),
  expect: {{
    timeout: Number(process.env.QA_UAT_EXPECT_TIMEOUT_MS ?? {QA_UAT_EXPECT_TIMEOUT_MS}),
  }},
  retries: Number(process.env.QA_UAT_RETRIES ?? {QA_UAT_RETRIES}),
  workers: Number(process.env.QA_UAT_WORKERS ?? {QA_UAT_WORKERS}),
  reporter: [
    ['html', {{ outputFolder: 'playwright-report', open: 'never' }}],
    ['junit', {{ outputFile: 'reports/junit.xml' }}],
    ['json', {{ outputFile: 'reports/playwright-results.json' }}],
    ['list'],
  ],
  use: {{
    trace: (process.env.QA_UAT_TRACE ?? '{QA_UAT_TRACE}') as 'on-first-retry' | 'always' | 'off' | 'retain-on-failure',
    screenshot: (process.env.QA_UAT_SCREENSHOT ?? '{QA_UAT_SCREENSHOT}') as 'only-on-failure' | 'always' | 'off',
    video: (process.env.QA_UAT_VIDEO ?? '{QA_UAT_VIDEO}') as 'retain-on-failure' | 'always' | 'off',
    headless: process.env.QA_UAT_HEADED !== 'true',
    actionTimeout: Number(process.env.QA_UAT_ACTION_TIMEOUT_MS ?? {QA_UAT_ACTION_TIMEOUT_MS}),
    navigationTimeout: Number(process.env.QA_UAT_NAV_TIMEOUT_MS ?? {QA_UAT_NAV_TIMEOUT_MS}),
    storageState: '.auth/agenda.json',
  }},
}});
"""


# ── Public API ────────────────────────────────────────────────────────────────

def generate_config(
    output_dir: Optional[Path] = None,
    env_overrides: Optional[dict] = None,
    dry_run: bool = False,
) -> dict:
    """
    Generate playwright.config.ts from environment variables and write it to disk.

    Parameters
    ----------
    output_dir : Path | None
        Directory where playwright.config.ts will be written.
        Defaults to the directory containing this file (tool root).
    env_overrides : dict | None
        Optional dict of env var overrides (for testing without mutating os.environ).
    dry_run : bool
        If True, return the config content without writing to disk.

    Returns
    -------
    dict with keys:
        ok: bool
        config_path: str — absolute path of written file (or would-be path if dry_run)
        content: str — the generated TypeScript content
        env_values: dict — resolved values used
        dry_run: bool
    """
    env_source = {**os.environ, **(env_overrides or {})}
    resolved = _resolve_env_values(env_source)
    errors = _validate_env_values(resolved)
    if errors:
        return {
            "ok": False,
            "error": "invalid_env_values",
            "message": f"Invalid env var values: {'; '.join(errors)}",
            "env_values": resolved,
        }

    content = _render_config(resolved)

    _output_dir = output_dir or Path(__file__).parent
    config_path = _output_dir / "playwright.config.ts"

    if not dry_run:
        try:
            _output_dir.mkdir(parents=True, exist_ok=True)
            config_path.write_text(content, encoding="utf-8")
            logger.info("playwright.config.ts written to %s", config_path)
        except OSError as exc:
            return {
                "ok": False,
                "error": "write_failed",
                "message": f"Could not write playwright.config.ts: {exc}",
                "config_path": str(config_path),
                "content": content,
                "env_values": resolved,
                "dry_run": dry_run,
            }

    return {
        "ok": True,
        "config_path": str(config_path.resolve()),
        "content": content,
        "env_values": resolved,
        "dry_run": dry_run,
    }


def get_env_defaults() -> dict:
    """Return a copy of the default env var values."""
    return dict(_ENV_DEFAULTS)


# ── Internals ─────────────────────────────────────────────────────────────────

def _resolve_env_values(env: dict) -> dict:
    """Read each supported env var from `env`, falling back to _ENV_DEFAULTS."""
    return {
        key: env.get(key, default)
        for key, default in _ENV_DEFAULTS.items()
    }


def _validate_env_values(resolved: dict) -> list[str]:
    """Validate that numeric fields are valid integers and string enums are valid."""
    errors: list[str] = []

    numeric_keys = {
        "QA_UAT_TEST_TIMEOUT_MS", "QA_UAT_EXPECT_TIMEOUT_MS",
        "QA_UAT_ACTION_TIMEOUT_MS", "QA_UAT_NAV_TIMEOUT_MS",
        "QA_UAT_GRID_TIMEOUT_MS", "QA_UAT_RETRIES", "QA_UAT_WORKERS",
    }
    for key in numeric_keys:
        val = resolved.get(key, "")
        try:
            n = int(val)
            if n < 0:
                errors.append(f"{key}={val!r} must be non-negative")
        except (ValueError, TypeError):
            errors.append(f"{key}={val!r} is not a valid integer")

    # Validate enum strings
    trace = resolved.get("QA_UAT_TRACE", "")
    if trace not in _VALID_TRACE:
        errors.append(f"QA_UAT_TRACE={trace!r} must be one of {sorted(_VALID_TRACE)}")

    screenshot = resolved.get("QA_UAT_SCREENSHOT", "")
    if screenshot not in _VALID_SCREENSHOT:
        errors.append(f"QA_UAT_SCREENSHOT={screenshot!r} must be one of {sorted(_VALID_SCREENSHOT)}")

    video = resolved.get("QA_UAT_VIDEO", "")
    if video not in _VALID_VIDEO:
        errors.append(f"QA_UAT_VIDEO={video!r} must be one of {sorted(_VALID_VIDEO)}")

    return errors


def _render_config(resolved: dict) -> str:
    """Render the TypeScript config template with resolved values."""
    # Use str.format_map — the template uses {KEY} placeholders
    # We escape the TS braces ({{}}) so they render as literal { }
    return _CONFIG_TEMPLATE.format_map(resolved)


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    import json
    import sys

    parser = argparse.ArgumentParser(
        description="playwright_config_writer — Generate playwright.config.ts from env vars"
    )
    parser.add_argument("--output-dir", help="Directory to write config (default: tool dir)")
    parser.add_argument("--dry-run", action="store_true", help="Print config without writing")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG, stream=sys.stderr)

    result = generate_config(
        output_dir=Path(args.output_dir) if args.output_dir else None,
        dry_run=args.dry_run,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    sys.exit(0 if result.get("ok") else 1)
