"""
selector_discovery.py — Determine the most robust Playwright selector for a DOM element.

Pure Python 3.8+ stdlib module — no external dependencies, no LLM, no network calls.
Used internally by ui_map_builder.py to choose selectors.

Usage:
    from selector_discovery import discover_selector

    result = discover_selector({
        "kind": "select",
        "role": "combobox",
        "label": "Empresa",
        "asp_id": "ddlEmpresa",
        "data_testid": None,
        "text": None,
    })
    # {"selector": "#ddlEmpresa", "robustness": "high", "fallbacks": [...], "warning": None}
"""
from __future__ import annotations

import re
from typing import Optional

# Regex to detect ASP.NET autogenerated IDs.
# Patterns: ctl00_..., ContentPlaceHolder1_..., _ctl\d+_, very long with $
_ASP_AUTOGEN_RE = re.compile(
    r"(ctl\d+|ContentPlaceHolder\d*|__VIEWSTATE|__EVENTVALIDATION|_ctl\d+_|\$)",
    re.IGNORECASE,
)
_MAX_STABLE_ID_LEN = 60


def _is_autogenerated_id(asp_id: str) -> bool:
    """Return True if asp_id looks like an ASP.NET autogenerated ID."""
    if not asp_id:
        return True
    if len(asp_id) > _MAX_STABLE_ID_LEN:
        return True
    return bool(_ASP_AUTOGEN_RE.search(asp_id))


def discover_selector(element: dict) -> dict:
    """
    Given element metadata, return the most robust Playwright selector possible.

    Priority (highest robustness first):
    1. getByTestId('<data_testid>')      — if data_testid present  → high
    2. getByRole('<role>', {name:'...'}) — if role + label unique   → high
    3. getByLabel('<label>')            — if label present          → high
    4. #<asp_id>                        — if ID is stable           → medium
    5. text=<text>                      — for buttons/links         → medium
    6. CSS positional fallback          — last resort               → low

    Args:
        element: dict with keys kind, role, label, asp_id, data_testid, text.
                 Missing keys are treated as None. Malformed input never raises.

    Returns:
        dict with keys: selector (str), robustness ("high"|"medium"|"low"),
                        fallbacks (list[str]), warning (str|None)
    """
    if not isinstance(element, dict):
        return _low_result("*", [], "requires_data_testid_from_dev")

    kind: Optional[str] = element.get("kind") or None
    role: Optional[str] = element.get("role") or None
    label: Optional[str] = (element.get("label") or "").strip() or None
    asp_id: Optional[str] = (element.get("asp_id") or "").strip() or None
    data_testid_raw: Optional[str] = (element.get("data_testid") or "").strip() or None
    text: Optional[str] = (element.get("text") or "").strip() or None

    # Empty data_testid string → treat as None (per spec §6)
    data_testid = data_testid_raw if data_testid_raw else None

    fallbacks: list[str] = []

    # ── 1. data-testid: highest confidence ───────────────────────────────────
    if data_testid:
        selector = f"getByTestId('{_esc(data_testid)}')"
        _append_fallbacks(fallbacks, role, label, asp_id, text, exclude=selector)
        return {"selector": selector, "robustness": "high", "fallbacks": fallbacks, "warning": None}

    # ── 2. getByRole with name ────────────────────────────────────────────────
    if role and label:
        selector = f"getByRole('{_esc(role)}', {{name: '{_esc(label)}'}})"
        _append_fallbacks(fallbacks, None, label, asp_id, text, exclude=selector)
        return {"selector": selector, "robustness": "high", "fallbacks": fallbacks, "warning": None}

    # ── 3. getByLabel ────────────────────────────────────────────────────────
    if label:
        selector = f"getByLabel('{_esc(label)}')"
        _append_fallbacks(fallbacks, None, None, asp_id, text, exclude=selector)
        return {"selector": selector, "robustness": "high", "fallbacks": fallbacks, "warning": None}

    # ── 4. stable asp_id → CSS id selector ───────────────────────────────────
    if asp_id and not _is_autogenerated_id(asp_id):
        selector = f"#{asp_id}"
        # Add attribute-ends-with as fallback (more lenient)
        fallbacks = [f"[id$='{_esc(asp_id)}']"]
        if text:
            fallbacks.append(f"text='{_esc(text)}'")
        return {"selector": selector, "robustness": "medium", "fallbacks": fallbacks, "warning": None}

    # ── 5. visible text (good for buttons/links) ─────────────────────────────
    if text and kind in ("button", "a", "link", None):
        selector = f"text='{_esc(text)}'"
        if asp_id:
            fallbacks = [f"[id$='{_esc(asp_id)}']"]
        return {"selector": selector, "robustness": "medium", "fallbacks": fallbacks, "warning": None}

    # ── 6. last resort: CSS by id ends-with or kind ──────────────────────────
    if asp_id:
        selector = f"[id$='{_esc(asp_id)}']"
    elif kind:
        selector = kind
    else:
        selector = "*"

    return _low_result(selector, fallbacks, "requires_data_testid_from_dev")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _esc(s: str) -> str:
    """Escape single quotes for Playwright selector strings."""
    return s.replace("'", "\\'")


def _low_result(selector: str, fallbacks: list, warning: str) -> dict:
    return {
        "selector": selector,
        "robustness": "low",
        "fallbacks": fallbacks,
        "warning": warning,
    }


def _append_fallbacks(
    fallbacks: list,
    role: Optional[str],
    label: Optional[str],
    asp_id: Optional[str],
    text: Optional[str],
    exclude: str,
) -> None:
    """Build ordered fallback list, skipping the already-chosen primary selector."""
    candidates = []
    if label:
        candidates.append(f"getByLabel('{_esc(label)}')")
    if asp_id and not _is_autogenerated_id(asp_id):
        candidates.append(f"#{asp_id}")
        candidates.append(f"[id$='{_esc(asp_id)}']")
    if text:
        candidates.append(f"text='{_esc(text)}'")
    for c in candidates:
        if c != exclude and c not in fallbacks:
            fallbacks.append(c)
