// ADO-57 P01 — Agenda con lotes USD - columna Prima visible
// Generated by playwright_test_generator.py v1.0.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/57/scenarios.json --ui-maps cache/ui_maps/ --out evidence/57/tests/
// Screen: FrmAgenda.aspx

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

test.describe('ADO-57 | P01 — Agenda con lotes USD - columna Prima visible', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p01 agenda_con_lotes_usd_-_columna_prima_visible', async ({ page }) => {
    // DATA: LODEUDA=1355030.88 AND OGMONEDA='US.D'

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    
    // - SELECTOR_NOT_FOUND
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/57/P01/step_00_setup.png' });

    // ACTION
    
    
    // [STEP 01] wait visible panel_c_updagenda
    await expect(page.locator('#c_updAgenda')).toBeVisible({ timeout: 10000 });
    
    
    
    // [STEP 02] fill input_desde with "1011240108601559"
    console.log('[STEP 02] fill input_desde');
    await page.locator("#c_abfDesde").fill('1011240108601559');;
    await page.screenshot({ path: 'evidence/57/P01/step_02_after.png' });
    
    
    
    // [STEP 03] click link_c_btnok
    console.log('[STEP 03] click link_c_btnok');
    await page.locator("#c_btnOk").click();
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/57/P01/step_03_after.png' });
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('#c_GridAgendaAut'), 'P01: grid_c_gridagendaaut debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_GridAgendaAut'), 'P01: grid_c_gridagendaaut debe ser visible').toBeVisible();
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    await page.screenshot({ path: 'evidence/57/P01/step_final_state.png' });
    await page.context().clearCookies();
  });
});