// ADO-57 P04 — Moneda local URGP (tasa=1) - sin conversion
// Generated by playwright_test_generator.py v1.0.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/57/scenarios.json --ui-maps cache/ui_maps/ --out evidence/57/tests/
// Screen: FrmAgenda.aspx

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

test.describe('ADO-57 | P04 — Moneda local URGP (tasa=1) - sin conversion', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p04 moneda_local_urgp_(tasa=1)_-_sin_conversion', async ({ page }) => {
    // DATA: OGMONEDA='URGP'

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    
    // - Lote con OGMONEDA='URGP' (CMVALOR=1.00 en RCAMBIO)
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/57/P04/step_00_setup.png' });

    // ACTION
    
    
    // [STEP 01] click link_c_btnok
    console.log('[STEP 01] click link_c_btnok');
    await page.locator("#c_btnOk").click();
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/57/P04/step_01_after.png' });
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('#c_lblAgendaAut'), 'P04: panel_c_lblagendaaut debe ser exactamente "LODEUDA usado directamente, sin multiplicacion efectiva"').toHaveText('LODEUDA usado directamente, sin multiplicacion efectiva');
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    await page.screenshot({ path: 'evidence/57/P04/step_final_state.png' });
    await page.context().clearCookies();
  });
});