// ADO-57 P06 — Agenda vacia
// Generated by playwright_test_generator.py v1.0.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/57/scenarios.json --ui-maps cache/ui_maps/ --out evidence/57/tests/
// Screen: FrmAgenda.aspx

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

test.describe('ADO-57 | P06 — Agenda vacia', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p06 agenda_vacia', async ({ page }) => {
    // DATA: N/A

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    
    // - Usuario sin lotes agendados activos
    

    // SETUP
    await page.goto(`${BASE_URL}FrmAgenda.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/57/P06/step_00_setup.png' });

    // ACTION
    
    
    // [STEP 01] wait visible grid_c_gridagendaaut
    await expect(page.locator('#c_GridAgendaAut')).toBeVisible({ timeout: 10000 });
    
    
    
    // [STEP 02] wait visible grid_c_gridagendausu
    await expect(page.locator('#c_GridAgendaUsu')).toBeVisible({ timeout: 10000 });
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('#c_GridAgendaAut'), 'P06: grid_c_gridagendaaut debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#c_GridAgendaUsu'), 'P06: grid_c_gridagendausu debe ser visible').toBeVisible();
    
    
    
    await expect(page.locator('#btnNext'), 'P06: link_btnnext no debe ser visible').toBeHidden();
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    await page.screenshot({ path: 'evidence/57/P06/step_final_state.png' });
    await page.context().clearCookies();
  });
});