/**
 * SeedPreviewPanel.tsx — Sprint 10 + 11: SQL Seed Preview + Human Approval
 *
 * Renders seed proposal scripts generated by sql_seed_generator.py when the
 * pipeline is in SQL_SEED_APPROVAL_REQUIRED state.
 *
 * Shows for each proposal:
 *   - Safety badge (SAFE / UNSAFE / unknown)
 *   - Safety checks grid (transaction, rollback, prod guard, seed_run_id, verification)
 *   - Blocking findings list (if any)
 *   - Seed script content (collapsible)
 *   - Cleanup script content (collapsible)
 *   - Approval notice: script always rolls back; operator must un-comment COMMIT
 *   - Inline SQL validator (re-validate edited scripts via /seed-proposal/validate)
 *   - Sprint 11: Approve button — sends SHA-256 for tamper-proof execution
 *
 * Security:
 *   - Approval requires explicit SHA-256 confirmation — prevents tampered execution.
 *   - dry_run=true by default — operator must un-check to enable real DB write.
 *   - Script content read from backend artifacts, never user-executed in browser.
 */
import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { QaUat } from "../api/endpoints";
import type { SeedProposal, SqlSafetyResult } from "../api/endpoints";
import styles from "./SeedPreviewPanel.module.css";

interface Props {
  runId: string;
  ticketId: number;
  scenarioId?: string;
}

export default function SeedPreviewPanel({ runId, ticketId, scenarioId }: Props) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["seed-proposals", runId, ticketId, scenarioId],
    queryFn: () => QaUat.listSeedProposals(runId, ticketId, scenarioId),
    staleTime: 30_000,
  });

  if (isLoading) {
    return (
      <div className={styles.panel}>
        <div className={styles.head}>
          SQL SEED PROPOSAL
          <div className={styles.headRight}>
            <span className={styles.spinner} />
          </div>
        </div>
        <div className={styles.loading}>Cargando propuestas SQL…</div>
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className={styles.panel}>
        <div className={styles.head}>SQL SEED PROPOSAL</div>
        <div className={styles.empty}>Error al cargar las propuestas de seed.</div>
      </div>
    );
  }

  const overallSafe =
    data.proposals.length > 0 &&
    data.proposals.every((p) => p.safety_result?.safe === true);
  const anyUnsafe = data.proposals.some((p) => p.safety_result?.safe === false);

  return (
    <div className={styles.panel}>
      <div className={styles.head}>
        <span>SQL SEED PROPOSAL</span>
        <div className={styles.headRight}>
          {data.proposals.length > 0 && (
            anyUnsafe ? (
              <span className={styles.badgeUnsafe}>✗ UNSAFE</span>
            ) : overallSafe ? (
              <span className={styles.badgeSafe}>✓ SAFE</span>
            ) : (
              <span className={styles.badgeUnknown}>? SIN VALIDAR</span>
            )
          )}
          <span style={{ fontSize: "0.72rem", color: "var(--muted,#888)" }}>
            {data.total} propuesta{data.total !== 1 ? "s" : ""}
          </span>
        </div>
      </div>

      <div className={styles.body}>
        {data.proposals.length === 0 && (
          <div className={styles.empty}>
            No hay propuestas SQL para este run aún.
            El pipeline genera scripts cuando el operador elige "Generar SQL Seed" en Data Readiness.
          </div>
        )}

        {data.proposals.map((proposal) => (
          <ProposalCard key={proposal.scenario_id} proposal={proposal} runId={runId} ticketId={ticketId} />
        ))}
      </div>
    </div>
  );
}

// ── ProposalCard ──────────────────────────────────────────────────────────────

interface ProposalCardProps {
  proposal: SeedProposal;
  runId: string;
  ticketId: number;
}

function ProposalCard({ proposal, runId, ticketId }: ProposalCardProps) {
  const [expanded, setExpanded] = useState(false);
  const [showCleanup, setShowCleanup] = useState(false);
  const [validatorSql, setValidatorSql] = useState("");
  const [validating, setValidating] = useState(false);
  const [validationResult, setValidationResult] = useState<SqlSafetyResult | null>(null);

  // Sprint 11: approval state
  const [approvalDryRun, setApprovalDryRun] = useState(true);
  const [approvalResult, setApprovalResult] = useState<Record<string, unknown> | null>(null);
  const qc = useQueryClient();

  const approveMutation = useMutation({
    mutationFn: () =>
      QaUat.approveSeedProposal({
        run_id: runId,
        ticket_id: ticketId,
        scenario_id: proposal.scenario_id,
        approved_sha256: proposal.safety_result?.script_sha256 ?? "",
        dry_run: approvalDryRun,
      }),
    onSuccess: (res) => {
      if (res.ok) {
        setApprovalResult(res.result ?? null);
        qc.invalidateQueries({ queryKey: ["seed-proposals", runId, ticketId] });
      }
    },
  });

  const sr = proposal.safety_result;

  async function handleValidate() {
    if (!validatorSql.trim()) return;
    setValidating(true);
    setValidationResult(null);
    try {
      const res = await QaUat.validateSeedScript(validatorSql, `operator:${proposal.scenario_id}`);
      if (res.ok) setValidationResult(res.result);
    } catch {
      // Silently ignore — user can retry
    } finally {
      setValidating(false);
    }
  }

  return (
    <div className={styles.proposalCard}>
      {/* Card header — toggles expansion */}
      <div className={styles.proposalHeader} onClick={() => setExpanded((v) => !v)}>
        <span className={styles.scenarioId}>{proposal.scenario_id}</span>
        {sr ? (
          sr.safe ? (
            <span className={styles.badgeSafe}>✓ SAFE</span>
          ) : (
            <span className={styles.badgeUnsafe}>✗ UNSAFE — {sr.blocking_findings.length} hallazgo{sr.blocking_findings.length !== 1 ? "s" : ""}</span>
          )
        ) : (
          <span className={styles.badgeUnknown}>Sin resultado de seguridad</span>
        )}
        <span className={styles.proposalChevron}>{expanded ? "▲" : "▼"}</span>
      </div>

      {expanded && (
        <>
          {/* Safety checks grid */}
          {sr && (
            <div className={styles.safetyChecks}>
              <CheckItem label="BEGIN TRANSACTION" ok={sr.checks.transaction_present} />
              <CheckItem label="ROLLBACK default" ok={sr.checks.rollback_default} />
              <CheckItem label="Guard anti-PROD" ok={sr.checks.prod_guard_present} />
              <CheckItem label="@SeedRunId" ok={sr.checks.seed_run_id_present} />
              <CheckItem label="Verification SELECT" ok={sr.checks.verification_select_present} />
              <CheckItem
                label="Sin keywords peligrosas"
                ok={sr.checks.dangerous_keywords.length === 0}
              />
            </div>
          )}

          {/* Blocking findings */}
          {sr && sr.blocking_findings.length > 0 && (
            <div className={styles.blockingFindings}>
              <div className={styles.blockingFindingsTitle}>
                Hallazgos bloqueantes ({sr.blocking_findings.length})
              </div>
              {sr.blocking_findings.map((f, i) => (
                <div key={i} className={styles.findingRow}>
                  <span className={styles.findingRule}>{f.rule}</span>
                  <span className={styles.findingDetail}>{f.detail}</span>
                </div>
              ))}
            </div>
          )}

          {/* Approval notice (only if safe) */}
          {sr?.safe && (
            <div className={styles.approveNotice}>
              <span>⚠</span>
              <span>
                El script <strong>no persiste datos</strong> — ROLLBACK TRANSACTION está activo.
                Para ejecutarlo, un operador debe revisar, descomentar <code>COMMIT TRANSACTION</code>
                y aprobarlo explícitamente en el proceso de Human Approval (Sprint 11).
              </span>
            </div>
          )}

          {/* Sprint 11: Human Approval action */}
          {sr?.safe && (
            <div className={styles.validatorSection}>
              <div className={styles.validatorLabel}>Aprobación humana (Sprint 11)</div>
              <div style={{ display: "flex", alignItems: "center", gap: "0.6rem", flexWrap: "wrap" }}>
                <label style={{ display: "flex", alignItems: "center", gap: "0.35rem", fontSize: "0.78rem", color: "var(--muted,#aaa)", cursor: "pointer" }}>
                  <input
                    type="checkbox"
                    checked={approvalDryRun}
                    onChange={(e) => setApprovalDryRun(e.target.checked)}
                    style={{ accentColor: "var(--accent,#7eb6ff)" }}
                  />
                  Dry-run (no toca BD)
                </label>
                <button
                  className={styles.validateBtn}
                  onClick={() => approveMutation.mutate()}
                  disabled={approveMutation.isPending || !sr.script_sha256}
                  title={
                    sr.script_sha256
                      ? `SHA-256: ${sr.script_sha256.slice(0, 16)}…`
                      : "SHA-256 no disponible — re-validar primero"
                  }
                >
                  {approveMutation.isPending ? <span className={styles.spinner} /> : "✓ Aprobar seed"}
                </button>
              </div>
              {approvalResult && (
                <div style={{ marginTop: "0.4rem" }}>
                  <span
                    className={
                      (approvalResult as any).verdict === "APPLIED"
                        ? styles.badgeSafe
                        : (approvalResult as any).verdict === "SKIPPED"
                        ? styles.badgeUnknown
                        : styles.badgeUnsafe
                    }
                  >
                    {(approvalResult as any).verdict}
                    {(approvalResult as any).reason ? ` — ${(approvalResult as any).reason}` : ""}
                    {(approvalResult as any).rows_inserted != null
                      ? ` — ${(approvalResult as any).rows_inserted} filas insertadas`
                      : ""}
                  </span>
                </div>
              )}
            </div>
          )}

          {/* Seed script */}
          <div className={styles.sqlBlock}>
            <div className={styles.sqlLabel}>Seed script</div>
            {proposal.script_content ? (
              <pre className={styles.sqlPre}>{proposal.script_content}</pre>
            ) : (
              <div className={styles.sqlTooLarge}>Script demasiado grande para mostrar inline ({proposal.script_path})</div>
            )}
          </div>

          {/* Cleanup script toggle */}
          {proposal.cleanup_path && (
            <div className={styles.sqlBlock}>
              <div
                className={styles.sqlLabel}
                style={{ cursor: "pointer" }}
                onClick={() => setShowCleanup((v) => !v)}
              >
                Cleanup script {showCleanup ? "▲" : "▼"}
              </div>
              {showCleanup && (
                proposal.cleanup_content ? (
                  <pre className={styles.sqlPre}>{proposal.cleanup_content}</pre>
                ) : (
                  <div className={styles.sqlTooLarge}>Script demasiado grande ({proposal.cleanup_path})</div>
                )
              )}
            </div>
          )}

          {/* Inline validator */}
          <div className={styles.validatorSection}>
            <div className={styles.validatorLabel}>Validar script editado</div>
            <textarea
              className={styles.validatorTextarea}
              placeholder="Pegá aquí el script SQL modificado para re-validar antes de enviarlo a aprobación…"
              value={validatorSql}
              onChange={(e) => setValidatorSql(e.target.value)}
              spellCheck={false}
            />
            <button
              className={styles.validateBtn}
              onClick={handleValidate}
              disabled={validating || !validatorSql.trim()}
            >
              {validating ? <span className={styles.spinner} /> : "Validar seguridad"}
            </button>

            {/* Inline validation result */}
            {validationResult && (
              <div>
                {validationResult.safe ? (
                  <span className={styles.badgeSafe}>✓ SAFE — Listo para aprobación humana</span>
                ) : (
                  <div>
                    <span className={styles.badgeUnsafe}>
                      ✗ UNSAFE — {validationResult.blocking_findings.length} hallazgo{validationResult.blocking_findings.length !== 1 ? "s" : ""}
                    </span>
                    <div className={styles.blockingFindings} style={{ marginTop: "0.4rem" }}>
                      {validationResult.blocking_findings.map((f, i) => (
                        <div key={i} className={styles.findingRow}>
                          <span className={styles.findingRule}>{f.rule}</span>
                          <span className={styles.findingDetail}>{f.detail}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}

// ── CheckItem ─────────────────────────────────────────────────────────────────

function CheckItem({ label, ok }: { label: string; ok: boolean }) {
  return (
    <div className={styles.checkItem}>
      <span className={ok ? styles.checkOk : styles.checkFail}>{ok ? "✓" : "✗"}</span>
      <span>{label}</span>
    </div>
  );
}
