// ADO--1 P01 — Verificar que se puede agregar un nuevo usuario desde el administrador
// Generated by playwright_test_generator.py v1.1.0
// DO NOT EDIT MANUALLY — regenerate with: python playwright_test_generator.py --scenarios evidence/-1/scenarios.json --ui-maps cache/ui_maps/ --out evidence/-1/tests/
// Screen: FrmGestionUsuarios.aspx


import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const BASE_URL = process.env.AGENDA_WEB_BASE_URL!;
const USER = process.env.AGENDA_WEB_USER!;
const PASS = process.env.AGENDA_WEB_PASS!;

if (!BASE_URL) throw new Error('AGENDA_WEB_BASE_URL env var is required');
if (!USER) throw new Error('AGENDA_WEB_USER env var is required');
if (!PASS) throw new Error('AGENDA_WEB_PASS env var is required');

// ORACLE_PROBES — generated from scenario.oraculos × ui_map.
// Consumed by the test.afterEach hook to write
// evidence/<ticket>/<sid>/assertions_<sid>.json with the actual values
// captured from the live DOM, regardless of whether the test passed,
// failed, or threw. uat_assertion_evaluator.py reads this file as the
// primary source of truth for expected/actual reconciliation; without
// it every oracle would default to status=review.
type OracleProbe = {
  oracle_id: number;
  target: string;
  tipo: string;
  expected: string | number | null;
  selector: string | null;  // CSS-ish; null for whole-page oracles
};
const ORACLE_PROBES: OracleProbe[] = [

  {
    oracle_id: 0,
    target: "panel_gvc_agenda_usu",
    tipo: "page_contains_text",
    expected: "USQA01",
    selector: null
  },

];
const ASSERTIONS_OUT_PATH = 'evidence/-1/P01/assertions_P01.json';

// STEP_BBOXES — accumulates bounding boxes of interacted elements per step.
// Written by test.afterEach to evidence/<ticket>/<sid>/step_bboxes.json and
// consumed by screenshot_annotator.py (Fase 2) to draw red boxes on screenshots.
type StepBboxEntry = {
  step_index: number;
  screenshot_path: string;
  target: string;
  bbox: { x: number; y: number; width: number; height: number } | null;
};
const STEP_BBOXES: StepBboxEntry[] = [];
const STEP_BBOXES_OUT_PATH = 'evidence/-1/P01/step_bboxes.json';


test.describe('ADO--1 | P01 — Verificar que se puede agregar un nuevo usuario desde el administrador', () => {

  test.beforeEach(async ({ page }) => {
    // SETUP: login via FrmLogin.aspx (AIS rendered controls)
    // Use noWaitAfter + waitForURL to avoid actionTimeout race on ASP.NET PostBack navigation
    await page.goto(`${BASE_URL}FrmLogin.aspx`, { waitUntil: 'load' });
    await page.fill('#c_abfUsuario', USER);
    await page.fill('#c_abfContrasena', PASS);
    await page.locator('#c_btnOk').click({ noWaitAfter: true });
    await page.waitForURL(/FrmAgenda/, { timeout: 25000 });
    await page.waitForLoadState('load', { timeout: 20000 });
  });

  test('p01 verificar_que_se_puede_agregar_un_nuevo_usuario_desde_el_adm', async ({ page }) => {
    // DATA: N/A

    // PRECONDITIONS (informational — verified by uat_precondition_checker.py before this test)
    

    // SETUP
    await page.goto(`${BASE_URL}FrmGestionUsuarios.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/-1/P01/step_00_setup.png' });

    // Expand "Búsqueda Avanzada" panel only when needed.
    // Some Agenda layouts don't expose data-toggle attrs, so use resilient fallback.
    const advancedPanel = page.locator('#c_pnlBusqueda');
    const firstFilter = page.locator('#c_ddlDebitoAuto, #c_abfCorredor, #c_abfNombreCliente, #c_abfRUC, #c_btnOk');
    let filtersReady = await firstFilter.first().isVisible().catch(() => false);
    if (!filtersReady) {
      const toggleByHeader = page.locator('.collapsible-header:has-text("Búsqueda Avanzada"), li:has-text("Búsqueda Avanzada") .collapsible-header').first();
      const toggleByData = page.locator('[data-toggle="collapse"][href="#c_pnlBusqueda"], [data-toggle="collapse"][data-target="#c_pnlBusqueda"]').first();
      const toggleByText = page.getByText('Búsqueda Avanzada', { exact: false }).first();

      if (await toggleByHeader.count()) {
        await toggleByHeader.scrollIntoViewIfNeeded();
        await toggleByHeader.click({ timeout: 5000, force: true });
      } else if (await toggleByData.count()) {
        await toggleByData.click({ timeout: 5000, force: true });
      } else if (await toggleByText.count()) {
        await toggleByText.click({ timeout: 5000, force: true });
      }

      if (await advancedPanel.count()) {
        await advancedPanel.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
      }
      filtersReady = await firstFilter.first().isVisible().catch(() => false);

      // Last-resort fallback for legacy WebForms layouts where the toggle
      // exists but does not update aria/visibility attributes consistently.
      if (!filtersReady && await advancedPanel.count()) {
        await page.evaluate(() => {
          const pnl = document.querySelector('#c_pnlBusqueda') as HTMLElement | null;
          if (pnl) {
            pnl.style.display = 'block';
            pnl.classList.add('active');
          }
        });
        filtersReady = await firstFilter.first().isVisible().catch(() => false);
      }
    }
    console.log('Advanced filters ready:', filtersReady);
    await page.screenshot({ path: 'screenshots/P01_panel_expanded.png' });

    // ACTION
    
    
    // [STEP 01] navigate to FrmAdministrador.aspx
    console.log('[STEP 01] navigate FrmAdministrador.aspx');
    await page.goto(`${BASE_URL}FrmAdministrador.aspx`, { waitUntil: 'load' });
    await page.screenshot({ path: 'evidence/-1/P01/step_01_after.png' });
    
    
    
    // [STEP 02] wait visible pb_step_1
    await expect(page.locator('#c_251')).toBeVisible({ timeout: 10000 });
    
    
    
    // [STEP 03] click pb_step_2
    console.log('[STEP 03] click pb_step_2');
    await page.locator("#c_251").click({ force: true });
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/-1/P01/step_03_after.png' });
    STEP_BBOXES.push({ step_index: 3, screenshot_path: 'evidence/-1/P01/step_03_after.png', target: "pb_step_2", bbox: await page.locator("#c_251").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 04] wait visible pb_step_3
    await expect(page.locator('#c_tvModOtorgadot41')).toBeVisible({ timeout: 10000 });
    
    
    
    // [STEP 05] click pb_step_4
    console.log('[STEP 05] click pb_step_4');
    await page.locator("a[data-tab-index='1']").click({ force: true });
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/-1/P01/step_05_after.png' });
    STEP_BBOXES.push({ step_index: 5, screenshot_path: 'evidence/-1/P01/step_05_after.png', target: "pb_step_4", bbox: await page.locator("a[data-tab-index='1']").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 06] wait visible pb_step_5
    await expect(page.locator('#c_abfCodigo')).toBeVisible({ timeout: 15000 });
    
    
    
    // [STEP 07] fill pb_step_6 with "USQA01"
    console.log('[STEP 07] fill pb_step_6');
    await page.locator("#c_abfCodigo").fill('USQA01', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_07_after.png' });
    STEP_BBOXES.push({ step_index: 7, screenshot_path: 'evidence/-1/P01/step_07_after.png', target: "pb_step_6", bbox: await page.locator("#c_abfCodigo").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 08] fill pb_step_7 with "QA Test User 01"
    console.log('[STEP 08] fill pb_step_7');
    await page.locator("#c_abfNombre").fill('QA Test User 01', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_08_after.png' });
    STEP_BBOXES.push({ step_index: 8, screenshot_path: 'evidence/-1/P01/step_08_after.png', target: "pb_step_7", bbox: await page.locator("#c_abfNombre").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 09] fill pb_step_8 with "5"
    console.log('[STEP 09] fill pb_step_8');
    await page.locator("#c_abfMaxLotes").fill('5', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_09_after.png' });
    STEP_BBOXES.push({ step_index: 9, screenshot_path: 'evidence/-1/P01/step_09_after.png', target: "pb_step_8", bbox: await page.locator("#c_abfMaxLotes").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 10] click pb_step_9
    console.log('[STEP 10] click pb_step_9');
    await page.locator("#c_btnAgregarUsuario").click({ force: true });
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/-1/P01/step_10_after.png' });
    STEP_BBOXES.push({ step_index: 10, screenshot_path: 'evidence/-1/P01/step_10_after.png', target: "pb_step_9", bbox: await page.locator("#c_btnAgregarUsuario").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 11] wait visible pb_step_10
    await expect(page.locator('#c_abfMdCodigo')).toBeVisible({ timeout: 30000 });
    
    
    
    // [STEP 12] select 0011 in pb_step_11
    console.log('[STEP 12] select pb_step_11');
    await page.locator("#c_ddlMdEmpleador").selectOption('0011', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_12_after.png' });
    STEP_BBOXES.push({ step_index: 12, screenshot_path: 'evidence/-1/P01/step_12_after.png', target: "pb_step_11", bbox: await page.locator("#c_ddlMdEmpleador").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 13] wait networkidle + UpdatePanel DOM settle
    await page.waitForLoadState('networkidle');
    // Wait for ASP.NET ScriptManager/UpdatePanel to finish processing the async PostBack response
    await page.waitForFunction(() => {
      try { return !Sys.WebForms.PageRequestManager.getInstance().get_isInAsyncPostBack(); } catch(e) { return true; }
    }, null, { timeout: 30000 }).catch(() => {});
    
    
    
    // [STEP 14] wait visible pb_step_13
    await expect(page.locator('#c_abfMdCodigo')).toBeVisible({ timeout: 30000 });
    
    
    
    // [STEP 15] fill pb_step_14 with "USQA01"
    console.log('[STEP 15] fill pb_step_14');
    await page.locator("#c_abfMdCodigo").fill('USQA01', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_15_after.png' });
    STEP_BBOXES.push({ step_index: 15, screenshot_path: 'evidence/-1/P01/step_15_after.png', target: "pb_step_14", bbox: await page.locator("#c_abfMdCodigo").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 16] fill pb_step_15 with "QA Test User 01"
    console.log('[STEP 16] fill pb_step_15');
    await page.locator("#c_abfMdNombre").fill('QA Test User 01', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_16_after.png' });
    STEP_BBOXES.push({ step_index: 16, screenshot_path: 'evidence/-1/P01/step_16_after.png', target: "pb_step_15", bbox: await page.locator("#c_abfMdNombre").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 17] fill pb_step_16 with "5"
    console.log('[STEP 17] fill pb_step_16');
    await page.locator("#c_abfMdMaxLotes").fill('5', { force: true });;
    await page.screenshot({ path: 'evidence/-1/P01/step_17_after.png' });
    STEP_BBOXES.push({ step_index: 17, screenshot_path: 'evidence/-1/P01/step_17_after.png', target: "pb_step_16", bbox: await page.locator("#c_abfMdMaxLotes").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 18] click pb_step_17
    console.log('[STEP 18] click pb_step_17');
    await page.locator("#c_btnGuardarUsuario").click({ force: true });
    await page.waitForLoadState('load');
    await page.screenshot({ path: 'evidence/-1/P01/step_18_after.png' });
    STEP_BBOXES.push({ step_index: 18, screenshot_path: 'evidence/-1/P01/step_18_after.png', target: "pb_step_17", bbox: await page.locator("#c_btnGuardarUsuario").boundingBox().catch(() => null) });
    
    
    
    
    // [STEP 19] wait networkidle + UpdatePanel DOM settle
    await page.waitForLoadState('networkidle');
    // Wait for ASP.NET ScriptManager/UpdatePanel to finish processing the async PostBack response
    await page.waitForFunction(() => {
      try { return !Sys.WebForms.PageRequestManager.getInstance().get_isInAsyncPostBack(); } catch(e) { return true; }
    }, null, { timeout: 30000 }).catch(() => {});
    
    

    // ASSERTIONS
    
    
    await expect(page.locator('body'), 'P01: página debe contener "USQA01"').toContainText('USQA01');
    
    

    // CLEANUP
    await page.context().clearCookies();
  });

  test.afterEach(async ({ page }) => {
    // Capture final state screenshot first — fail-safe even if the page is
    // mid-PostBack.
    try {
      await page.screenshot({
        path: 'evidence/-1/P01/step_final_state.png',
      });
    } catch (_e) {
      // ignore — page may be closed or navigating
    }

    // ASSERTIONS EVIDENCE — capture actual values for every oracle so
    // uat_assertion_evaluator.py can reconcile expected vs actual without
    // relying on Playwright's pass/fail (which conflates product defects
    // with pipeline defects).
    const captured: any[] = [];
    for (const probe of ORACLE_PROBES) {
      const entry: any = {
        oracle_id: probe.oracle_id,
        target: probe.target,
        tipo: probe.tipo,
        expected: probe.expected,
      };
      try {
        if (probe.selector === null) {
          // Whole-page oracle: capture the body text once (truncated).
          const bodyText = (await page.locator('body').innerText({ timeout: 2000 })) || '';
          entry.actual_text = bodyText.slice(0, 4000);
          entry.visible = true;
        } else {
          const loc = page.locator(probe.selector);
          // count
          const count = await loc.count();
          entry.count = count;
          if (count === 0) {
            entry.visible = false;
            entry.actual_text = null;
          } else {
            entry.visible = await loc.first().isVisible({ timeout: 2000 });
            // value (form controls)
            try {
              entry.value = await loc.first().inputValue({ timeout: 1000 });
            } catch (_e) { /* not a form control */ }
            // textContent
            try {
              const txt = (await loc.first().innerText({ timeout: 1500 })) || '';
              entry.actual_text = txt.slice(0, 1000);
            } catch (_e) {
              entry.actual_text = null;
            }
            // disabled / state
            try {
              entry.state = (await loc.first().isDisabled({ timeout: 500 })) ? 'disabled' : 'enabled';
            } catch (_e) { /* ignore */ }
          }
        }
      } catch (e: any) {
        entry.capture_error = String(e && e.message ? e.message : e).slice(0, 300);
      }
      captured.push(entry);
    }

    // Persist assertions_<sid>.json. mkdir is safe-recursive; failures here
    // must not break the test runner.
    try {
      const outPath = path.resolve(process.cwd(), ASSERTIONS_OUT_PATH);
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(
        outPath,
        JSON.stringify(
          { scenario_id: 'P01', assertions: captured },
          null, 2,
        ),
        'utf-8',
      );
    } catch (e) {
      console.error('[afterEach] could not persist assertions json:', e);
    }

    // Persist step_bboxes.json for screenshot_annotator.py (Fase 2).
    // Non-fatal: if this fails the pipeline continues without annotations.
    if (STEP_BBOXES.length > 0) {
      try {
        const bboxOutPath = path.resolve(process.cwd(), STEP_BBOXES_OUT_PATH);
        fs.mkdirSync(path.dirname(bboxOutPath), { recursive: true });
        fs.writeFileSync(bboxOutPath, JSON.stringify(STEP_BBOXES, null, 2), 'utf-8');
      } catch (e) {
        console.error('[afterEach] could not persist step_bboxes json:', e);
      }
    }


    await page.context().clearCookies();
  });
});